/* Generated by Yosys 0.20 (git sha1 4fcb95ed087, clang  -fPIC -Os) */

(* dynports =  1  *)
(* src = "dlatch.v:1.1-15.10" *)
module m_0(CLR, CLR_t, D, D_t, CLK, CLK_t, Q, Q_t, SET, SET_t);
  (* src = "dlatch.v:6.7-6.9" *)
  input CLK;
  wire CLK;
  (* src = "dlatch.v:7.19-7.20" *)
  input [1:0] CLR;
  wire [1:0] CLR;
  (* src = "dlatch.v:7.19-7.20" *)
  input [1:0] D;
  wire [1:0] D;
  (* src = "dlatch.v:8.24-8.25" *)
  output [1:0] Q;
  reg [1:0] Q;
  (* src = "dlatch.v:7.19-7.20" *)
  input [1:0] SET;
  wire [1:0] SET;
  (* src = "dlatch.v:10.1-13.4" *)
  input [31:0] CLK_t;
  input [31:0] D_t;
  input [31:0] SET_t;
  input [31:0] CLR_t;
  output reg [31:0] Q_t;

  initial begin
      Q_t = 0;
  end

  always @(posedge CLK, posedge SET[0], posedge CLR[0])begin
    if (CLR[0]) begin
    Q[0] <= 1'b0;
    Q_t <= CLR_t;
    end
    else if (SET[0])begin
     Q[0] <= 1'b1;
     Q_t <= SET_t;
     end
    else begin
    Q[0] <= D[0];
    Q_t <= D_t;
    end
    end
  (* src = "dlatch.v:10.1-13.4" *)
  always @(posedge CLK, posedge SET[1], posedge CLR[1])begin
    if (CLR[1]) begin
    Q[1] <= 1'b0;
    Q_t <= CLR_t;
    end
    else if (SET[1])begin
     Q[1] <= 1'b1;
     Q_t <= SET_t;
     end
    else begin
    Q[1] <= D[1];
    Q_t <= D_t;
    end
    end
endmodule
