/* Generated by Yosys 0.39+1 (git sha1 b3124f30e, x86_64-w64-mingw32-g++ 13.2.1 -Os) */

module eth_fifo(data_in, data_out, clk, reset, write, read, clear, almost_full, full, almost_empty, empty, cnt);
  wire [31:0] \$0$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$22 ;
  wire [31:0] \$0$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$23 ;
  wire [2:0] \$0$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$24 ;
  wire [31:0] \$0$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$25 ;
  wire [31:0] \$0$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$26 ;
  wire [3:0] \$0\cnt[3:0] ;
  wire [31:0] \$0\data_out[31:0] ;
  wire [2:0] \$0\read_pointer[2:0] ;
  wire [2:0] \$0\write_pointer[2:0] ;
  wire [31:0] \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 ;
  wire [31:0] \$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 ;
  wire [2:0] \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30 ;
  wire [31:0] \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 ;
  wire [31:0] \$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 ;
  wire [2:0] \$2$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$35 ;
  wire [31:0] \$2$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$36 ;
  wire [31:0] \$2$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$37 ;
  wire [31:0] \$add$eth_fifo.v:109$7_Y ;
  wire [2:0] \$add$eth_fifo.v:122$11_Y ;
  wire [2:0] \$add$eth_fifo.v:134$15_Y ;
  wire \$and$eth_fifo.v:121$10_Y ;
  wire \$and$eth_fifo.v:133$14_Y ;
  wire \$and$eth_fifo.v:167$27_Y ;
  wire \$and$eth_fifo.v:170$34_Y ;
  wire \$eq$eth_fifo.v:138$18_Y ;
  wire \$eq$eth_fifo.v:139$19_Y ;
  wire [31:0] \$memrd$\fifo$eth_fifo.v:178$39_DATA ;
  wire [31:0] \$memrd$\fifo$eth_fifo.v:180$40_DATA ;
  reg [31:0] \$memwr$\fifo$eth_fifo.v:168$1_DATA ;
  reg [31:0] \$memwr$\fifo$eth_fifo.v:168$1_EN ;
  reg [2:0] \$memwr$\fifo$eth_fifo.v:171$2_ADDR ;
  reg [31:0] \$memwr$\fifo$eth_fifo.v:171$2_DATA ;
  reg [31:0] \$memwr$\fifo$eth_fifo.v:171$2_EN ;
  wire \$not$eth_fifo.v:121$9_Y ;
  wire \$not$eth_fifo.v:133$13_Y ;
  wire \$not$eth_fifo.v:137$17_Y ;
  wire \$not$eth_fifo.v:170$33_Y ;
  wire [31:0] \$procmux$42_Y ;
  wire \$procmux$43_CMP ;
  wire [31:0] \$procmux$45_Y ;
  wire \$procmux$46_CMP ;
  wire [31:0] \$procmux$48_Y ;
  wire \$procmux$49_CMP ;
  wire [31:0] \$procmux$51_Y ;
  wire \$procmux$52_CMP ;
  wire [31:0] \$procmux$54_Y ;
  wire \$procmux$55_CMP ;
  wire [2:0] \$procmux$57_Y ;
  wire \$procmux$58_CMP ;
  wire [2:0] \$procmux$60_Y ;
  wire \$procmux$61_CMP ;
  wire [31:0] \$procmux$63_Y ;
  wire \$procmux$64_CMP ;
  wire [31:0] \$procmux$66_Y ;
  wire \$procmux$67_CMP ;
  wire [31:0] \$procmux$69_Y ;
  wire \$procmux$70_CMP ;
  wire [31:0] \$procmux$72_Y ;
  wire \$procmux$73_CMP ;
  wire [2:0] \$procmux$75_Y ;
  wire \$procmux$76_CMP ;
  wire [2:0] \$procmux$77_Y ;
  wire \$procmux$78_CMP ;
  wire [2:0] \$procmux$80_Y ;
  wire \$procmux$81_CMP ;
  wire [2:0] \$procmux$82_Y ;
  wire \$procmux$83_CMP ;
  wire [2:0] \$procmux$85_Y ;
  wire \$procmux$86_CMP ;
  wire [3:0] \$procmux$88_Y ;
  wire \$procmux$89_CMP ;
  wire [3:0] \$procmux$90_Y ;
  wire \$procmux$91_CMP ;
  wire [3:0] \$procmux$93_Y ;
  wire \$procmux$94_CMP ;
  wire \$reduce_and$eth_fifo.v:140$20_Y ;
  wire \$reduce_or$eth_fifo.v:137$16_Y ;
  wire [31:0] \$sub$eth_fifo.v:107$6_Y ;
  wire \$xor$eth_fifo.v:103$4_Y ;
  wire \$xor$eth_fifo.v:105$5_Y ;
  output almost_empty;
  wire almost_empty;
  output almost_full;
  wire almost_full;
  input clear;
  wire clear;
  input clk;
  wire clk;
  output [3:0] cnt;
  reg [3:0] cnt;
  input [31:0] data_in;
  wire [31:0] data_in;
  output [31:0] data_out;
  reg [31:0] data_out;
  output empty;
  wire empty;
  output full;
  wire full;
  input read;
  wire read;
  reg [2:0] read_pointer;
  input reset;
  wire reset;
  input write;
  wire write;
  reg [2:0] write_pointer;
  reg [31:0] fifo [7:0];
  always @(posedge clk) begin
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [0])
      fifo[32'd0][0:0] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [0];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [1])
      fifo[32'd0][1:1] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [1];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [2])
      fifo[32'd0][2:2] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [2];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [3])
      fifo[32'd0][3:3] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [3];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [4])
      fifo[32'd0][4:4] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [4];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [5])
      fifo[32'd0][5:5] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [5];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [6])
      fifo[32'd0][6:6] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [6];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [7])
      fifo[32'd0][7:7] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [7];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [8])
      fifo[32'd0][8:8] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [8];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [9])
      fifo[32'd0][9:9] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [9];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [10])
      fifo[32'd0][10:10] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [10];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [11])
      fifo[32'd0][11:11] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [11];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [12])
      fifo[32'd0][12:12] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [12];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [13])
      fifo[32'd0][13:13] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [13];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [14])
      fifo[32'd0][14:14] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [14];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [15])
      fifo[32'd0][15:15] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [15];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [16])
      fifo[32'd0][16:16] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [16];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [17])
      fifo[32'd0][17:17] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [17];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [18])
      fifo[32'd0][18:18] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [18];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [19])
      fifo[32'd0][19:19] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [19];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [20])
      fifo[32'd0][20:20] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [20];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [21])
      fifo[32'd0][21:21] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [21];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [22])
      fifo[32'd0][22:22] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [22];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [23])
      fifo[32'd0][23:23] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [23];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [24])
      fifo[32'd0][24:24] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [24];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [25])
      fifo[32'd0][25:25] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [25];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [26])
      fifo[32'd0][26:26] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [26];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [27])
      fifo[32'd0][27:27] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [27];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [28])
      fifo[32'd0][28:28] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [28];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [29])
      fifo[32'd0][29:29] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [29];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [30])
      fifo[32'd0][30:30] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [30];
    if (\$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 [31])
      fifo[32'd0][31:31] <= \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 [31];
  end
  always @(posedge clk) begin
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [0])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][0:0] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [0];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [1])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][1:1] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [1];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [2])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][2:2] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [2];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [3])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][3:3] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [3];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [4])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][4:4] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [4];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [5])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][5:5] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [5];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [6])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][6:6] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [6];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [7])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][7:7] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [7];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [8])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][8:8] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [8];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [9])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][9:9] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [9];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [10])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][10:10] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [10];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [11])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][11:11] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [11];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [12])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][12:12] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [12];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [13])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][13:13] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [13];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [14])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][14:14] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [14];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [15])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][15:15] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [15];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [16])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][16:16] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [16];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [17])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][17:17] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [17];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [18])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][18:18] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [18];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [19])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][19:19] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [19];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [20])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][20:20] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [20];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [21])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][21:21] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [21];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [22])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][22:22] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [22];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [23])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][23:23] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [23];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [24])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][24:24] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [24];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [25])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][25:25] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [25];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [26])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][26:26] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [26];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [27])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][27:27] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [27];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [28])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][28:28] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [28];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [29])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][29:29] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [29];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [30])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][30:30] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [30];
    if (\$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 [31])
      fifo[{ 29'h00000000, \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  }][31:31] <= \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 [31];
  end
  assign \$memrd$\fifo$eth_fifo.v:178$39_DATA  = fifo[32'd0];
  assign \$memrd$\fifo$eth_fifo.v:180$40_DATA  = fifo[{ 29'h00000000, read_pointer }];
  assign \$add$eth_fifo.v:109$7_Y  = cnt + 32'd1;
  assign \$add$eth_fifo.v:122$11_Y  = read_pointer + 1'h1;
  assign \$add$eth_fifo.v:134$15_Y  = write_pointer + 1'h1;
  assign \$and$eth_fifo.v:121$10_Y  = read & \$not$eth_fifo.v:121$9_Y ;
  assign \$and$eth_fifo.v:133$14_Y  = write & \$not$eth_fifo.v:133$13_Y ;
  assign \$and$eth_fifo.v:167$27_Y  = write & clear;
  assign \$and$eth_fifo.v:170$34_Y  = write & \$not$eth_fifo.v:170$33_Y ;
  assign \$eq$eth_fifo.v:138$18_Y  = cnt == 4'h1;
  assign \$eq$eth_fifo.v:139$19_Y  = cnt == 4'h8;
  assign \$not$eth_fifo.v:133$13_Y  = ~ full;
  assign \$not$eth_fifo.v:137$17_Y  = ~ \$reduce_or$eth_fifo.v:137$16_Y ;
  assign \$not$eth_fifo.v:170$33_Y  = ~ full;
  always @(posedge clk)
    \$memwr$\fifo$eth_fifo.v:171$2_EN  <= \$procmux$69_Y ;
  always @(posedge clk, posedge reset)
    if (reset) write_pointer <= 3'h0;
    else write_pointer <= \$procmux$80_Y ;
  always @(posedge clk, posedge reset)
    if (reset) read_pointer <= 3'h0;
    else read_pointer <= \$procmux$85_Y ;
  always @(posedge clk, posedge reset)
    if (reset) cnt <= 4'h0;
    else cnt <= \$procmux$93_Y ;
  always @(posedge clk)
    data_out <= \$procmux$42_Y ;
  always @(posedge clk)
    \$memwr$\fifo$eth_fifo.v:168$1_DATA  <= \$procmux$66_Y ;
  always @(posedge clk)
    \$memwr$\fifo$eth_fifo.v:168$1_EN  <= \$procmux$63_Y ;
  always @(posedge clk)
    \$memwr$\fifo$eth_fifo.v:171$2_ADDR  <= \$procmux$75_Y ;
  always @(posedge clk)
    \$memwr$\fifo$eth_fifo.v:171$2_DATA  <= \$procmux$72_Y ;
  assign \$procmux$42_Y  = \$procmux$43_CMP  ? \$memrd$\fifo$eth_fifo.v:178$39_DATA  : \$memrd$\fifo$eth_fifo.v:180$40_DATA ;
  assign \$procmux$45_Y  = \$procmux$46_CMP  ? 32'd4294967295 : 32'd0;
  assign \$procmux$48_Y  = \$procmux$49_CMP  ? 32'hxxxxxxxx : \$procmux$45_Y ;
  assign \$procmux$51_Y  = \$procmux$52_CMP  ? data_in : 32'hxxxxxxxx;
  assign \$procmux$54_Y  = \$procmux$55_CMP  ? 32'hxxxxxxxx : \$procmux$51_Y ;
  assign \$procmux$57_Y  = \$procmux$58_CMP  ? write_pointer : 3'hx;
  assign \$procmux$60_Y  = \$procmux$61_CMP  ? 3'hx : \$procmux$57_Y ;
  assign \$procmux$63_Y  = \$procmux$64_CMP  ? 32'd4294967295 : 32'd0;
  assign \$procmux$66_Y  = \$procmux$67_CMP  ? data_in : 32'hxxxxxxxx;
  assign \$procmux$69_Y  = \$procmux$70_CMP  ? 32'd0 : \$2$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$37 ;
  assign \$procmux$72_Y  = \$procmux$73_CMP  ? 32'hxxxxxxxx : \$2$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$36 ;
  assign \$procmux$75_Y  = \$procmux$76_CMP  ? 3'hx : \$2$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$35 ;
  assign \$procmux$77_Y  = \$procmux$78_CMP  ? \$add$eth_fifo.v:134$15_Y  : write_pointer;
  assign \$procmux$80_Y  = \$procmux$81_CMP  ? { 2'h0, write } : \$procmux$77_Y ;
  assign \$procmux$82_Y  = \$procmux$83_CMP  ? \$add$eth_fifo.v:122$11_Y  : read_pointer;
  assign \$procmux$85_Y  = \$procmux$86_CMP  ? { 2'h0, read } : \$procmux$82_Y ;
  assign \$procmux$88_Y  = \$procmux$89_CMP  ? \$sub$eth_fifo.v:107$6_Y [3:0] : \$add$eth_fifo.v:109$7_Y [3:0];
  assign \$procmux$90_Y  = \$procmux$91_CMP  ? \$procmux$88_Y  : cnt;
  assign \$procmux$93_Y  = \$procmux$94_CMP  ? { 3'h0, \$xor$eth_fifo.v:103$4_Y  } : \$procmux$90_Y ;
  assign \$reduce_and$eth_fifo.v:140$20_Y  = & cnt[2:0];
  assign \$reduce_or$eth_fifo.v:137$16_Y  = | cnt;
  assign \$sub$eth_fifo.v:107$6_Y  = cnt - 32'd1;
  assign \$xor$eth_fifo.v:103$4_Y  = read ^ write;
  assign \$xor$eth_fifo.v:105$5_Y  = read ^ write;
  assign empty = \$not$eth_fifo.v:137$17_Y ;
  assign almost_empty = \$eq$eth_fifo.v:138$18_Y ;
  assign full = \$eq$eth_fifo.v:139$19_Y ;
  assign almost_full = \$reduce_and$eth_fifo.v:140$20_Y ;
  assign \$0$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$26  = \$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32 ;
  assign \$0$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$25  = \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31 ;
  assign \$0$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$24  = \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30 ;
  assign \$0$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$23  = \$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29 ;
  assign \$0$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$22  = \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28 ;
  assign \$procmux$43_CMP  = clear;
  assign \$0\data_out[31:0]  = \$procmux$42_Y ;
  assign \$procmux$46_CMP  = \$and$eth_fifo.v:170$34_Y ;
  assign \$procmux$49_CMP  = \$and$eth_fifo.v:167$27_Y ;
  assign \$2$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$37  = \$procmux$48_Y ;
  assign \$procmux$52_CMP  = \$and$eth_fifo.v:170$34_Y ;
  assign \$procmux$55_CMP  = \$and$eth_fifo.v:167$27_Y ;
  assign \$2$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$36  = \$procmux$54_Y ;
  assign \$procmux$58_CMP  = \$and$eth_fifo.v:170$34_Y ;
  assign \$procmux$61_CMP  = \$and$eth_fifo.v:167$27_Y ;
  assign \$2$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$35  = \$procmux$60_Y ;
  assign \$procmux$64_CMP  = \$and$eth_fifo.v:167$27_Y ;
  assign \$1$memwr$\fifo$eth_fifo.v:168$1_EN[31:0]$29  = \$procmux$63_Y ;
  assign \$procmux$67_CMP  = \$and$eth_fifo.v:167$27_Y ;
  assign \$1$memwr$\fifo$eth_fifo.v:168$1_DATA[31:0]$28  = \$procmux$66_Y ;
  assign \$procmux$70_CMP  = \$and$eth_fifo.v:167$27_Y ;
  assign \$1$memwr$\fifo$eth_fifo.v:171$2_EN[31:0]$32  = \$procmux$69_Y ;
  assign \$procmux$73_CMP  = \$and$eth_fifo.v:167$27_Y ;
  assign \$1$memwr$\fifo$eth_fifo.v:171$2_DATA[31:0]$31  = \$procmux$72_Y ;
  assign \$procmux$76_CMP  = \$and$eth_fifo.v:167$27_Y ;
  assign \$1$memwr$\fifo$eth_fifo.v:171$2_ADDR[2:0]$30  = \$procmux$75_Y ;
  assign \$procmux$78_CMP  = \$and$eth_fifo.v:133$14_Y ;
  assign \$procmux$81_CMP  = clear;
  assign \$0\write_pointer[2:0]  = \$procmux$80_Y ;
  assign \$procmux$83_CMP  = \$and$eth_fifo.v:121$10_Y ;
  assign \$procmux$86_CMP  = clear;
  assign \$0\read_pointer[2:0]  = \$procmux$85_Y ;
  assign \$procmux$89_CMP  = read;
  assign \$procmux$91_CMP  = \$xor$eth_fifo.v:105$5_Y ;
  assign \$procmux$94_CMP  = clear;
  assign \$0\cnt[3:0]  = \$procmux$93_Y ;
  assign \$not$eth_fifo.v:121$9_Y  = \$reduce_or$eth_fifo.v:137$16_Y ;
endmodule
