/* Generated by Yosys 0.20 (git sha1 4fcb95ed087, clang  -fPIC -Os) */

(* src = "shift.v:1.1-29.10" *)
module m_0(A, B, Y);
  (* src = "shift.v:9.25-9.26" *)
  input [1:0] A;
  wire [1:0] A;
  (* src = "shift.v:10.25-10.26" *)
  input [1:0] B;
  wire [1:0] B;
  (* src = "shift.v:11.26-11.27" *)
  output [1:0] Y;
  wire [1:0] Y;
  assign Y = $signed(B) < 0 ? $signed(A) << - B : $signed(A) >> B;
endmodule
