/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */

(* top =  1  *)
(* src = "SPI_Master.v:1.1-162.10" *)
module SPI_Master(clk, start, load, data_to_write, slave_address, cpol, cpha, MISO, SCLK, CS1, CS2, CS3, MOSI, data_read, slave_start);
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _000_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _001_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _002_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _003_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _004_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _005_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _006_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _007_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _008_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _009_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [7:0] _010_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _011_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _012_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _013_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [7:0] _014_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _015_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _016_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _017_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _018_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _019_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _020_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _021_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _022_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _023_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _024_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _025_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [7:0] _026_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _027_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _028_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _029_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _030_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _031_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _032_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _033_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _034_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [7:0] _035_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _036_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _037_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _038_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _039_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _040_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _041_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [7:0] _042_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _043_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [7:0] _044_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _045_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _046_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _047_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _048_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [7:0] _049_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _050_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _051_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [7:0] _052_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _053_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _054_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _055_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _056_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [7:0] _057_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _058_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _059_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [7:0] _060_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _061_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _062_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _063_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _064_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [7:0] _065_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _066_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _067_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [7:0] _068_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _069_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _070_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _071_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _072_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [7:0] _073_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _074_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire _075_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _076_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  wire [31:0] _077_;
  (* src = "SPI_Master.v:113.41-113.64" *)
  wire [31:0] _078_;
  (* src = "SPI_Master.v:120.33-120.41" *)
  wire [31:0] _079_;
  (* src = "SPI_Master.v:126.33-126.41" *)
  wire [31:0] _080_;
  (* src = "SPI_Master.v:136.41-136.64" *)
  wire [31:0] _081_;
  (* src = "SPI_Master.v:144.31-144.39" *)
  wire [31:0] _082_;
  (* src = "SPI_Master.v:149.33-149.41" *)
  wire [31:0] _083_;
  (* src = "SPI_Master.v:61.25-61.32" *)
  wire [31:0] _084_;
  (* src = "SPI_Master.v:72.10-72.18" *)
  wire [31:0] _085_;
  (* src = "SPI_Master.v:88.28-88.37" *)
  wire [31:0] _086_;
  (* src = "SPI_Master.v:97.28-97.35" *)
  wire [31:0] _087_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _088_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _089_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _090_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _091_;
  (* src = "SPI_Master.v:111.20-111.30" *)
  wire _092_;
  (* src = "SPI_Master.v:117.20-117.33" *)
  wire _093_;
  (* src = "SPI_Master.v:122.30-122.39" *)
  wire _094_;
  (* src = "SPI_Master.v:134.20-134.30" *)
  wire _095_;
  (* src = "SPI_Master.v:140.20-140.33" *)
  wire _096_;
  (* src = "SPI_Master.v:146.38-146.47" *)
  wire _097_;
  (* src = "SPI_Master.v:155.4-155.13" *)
  wire _098_;
  (* src = "SPI_Master.v:26.4-26.13" *)
  wire _099_;
  (* src = "SPI_Master.v:32.4-32.28" *)
  wire _100_;
  (* src = "SPI_Master.v:58.12-58.20" *)
  wire _101_;
  (* src = "SPI_Master.v:79.20-79.28" *)
  wire _102_;
  (* src = "SPI_Master.v:117.20-117.46" *)
  wire _103_;
  (* src = "SPI_Master.v:122.13-122.39" *)
  wire _104_;
  (* src = "SPI_Master.v:140.20-140.46" *)
  wire _105_;
  (* src = "SPI_Master.v:146.21-146.47" *)
  wire _106_;
  (* src = "SPI_Master.v:26.4-26.38" *)
  wire _107_;
  (* src = "SPI_Master.v:38.4-38.31" *)
  wire _108_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _109_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _110_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _111_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _112_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _113_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _114_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _115_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _116_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _117_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _118_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _119_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _120_;
  (* src = "SPI_Master.v:78.24-78.29" *)
  wire _121_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _122_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _123_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _124_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _125_;
  wire _126_;
  wire [31:0] _127_;
  wire [31:0] _128_;
  wire [31:0] _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire [31:0] _133_;
  wire [31:0] _134_;
  wire [31:0] _135_;
  wire [7:0] _136_;
  wire [7:0] _137_;
  wire [7:0] _138_;
  wire [7:0] _139_;
  wire [7:0] _140_;
  wire [7:0] _141_;
  wire [31:0] _142_;
  wire [31:0] _143_;
  wire [31:0] _144_;
  wire [31:0] _145_;
  wire [31:0] _146_;
  wire [31:0] _147_;
  wire [31:0] _148_;
  wire [31:0] _149_;
  wire _150_;
  wire _151_;
  wire [7:0] _152_;
  wire [7:0] _153_;
  wire [7:0] _154_;
  wire [7:0] _155_;
  wire [31:0] _156_;
  wire [31:0] _157_;
  wire [31:0] _158_;
  wire [31:0] _159_;
  wire [31:0] _160_;
  wire [7:0] _161_;
  wire [7:0] _162_;
  wire [7:0] _163_;
  wire [7:0] _164_;
  wire [7:0] _165_;
  wire [7:0] _166_;
  wire [31:0] _167_;
  wire [31:0] _168_;
  wire [31:0] _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire [31:0] _173_;
  wire [31:0] _174_;
  wire [31:0] _175_;
  wire [31:0] _176_;
  wire [31:0] _177_;
  wire [31:0] _178_;
  wire [31:0] _179_;
  wire [31:0] _180_;
  wire [7:0] _181_;
  wire [7:0] _182_;
  wire [7:0] _183_;
  wire [7:0] _184_;
  wire _185_;
  wire _186_;
  wire [31:0] _187_;
  wire [31:0] _188_;
  wire [31:0] _189_;
  wire [31:0] _190_;
  wire [7:0] _191_;
  wire [7:0] _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire [31:0] _200_;
  wire [31:0] _201_;
  wire [31:0] _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire [31:0] _209_;
  wire [31:0] _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire [31:0] _215_;
  wire [31:0] _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire [31:0] _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire [31:0] _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _238_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _239_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _240_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _241_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _242_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _243_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _244_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [7:0] _245_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire _246_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire _247_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _248_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _249_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _250_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _251_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _252_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _253_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _254_;
  (* src = "SPI_Master.v:0.0-0.0" *)
  wire [32:0] _255_;
  (* src = "SPI_Master.v:14.5-14.9" *)
  reg CPHA;
  (* src = "SPI_Master.v:13.5-13.9" *)
  reg CPOL;
  (* src = "SPI_Master.v:6.50-6.53" *)
  output CS1;
  reg CS1;
  (* src = "SPI_Master.v:6.67-6.70" *)
  output CS2;
  reg CS2;
  (* src = "SPI_Master.v:6.84-6.87" *)
  output CS3;
  reg CS3;
  (* src = "SPI_Master.v:4.27-4.31" *)
  input MISO;
  wire MISO;
  (* src = "SPI_Master.v:7.32-7.36" *)
  output MOSI;
  reg MOSI;
  (* src = "SPI_Master.v:6.32-6.36" *)
  output SCLK;
  reg SCLK;
  (* src = "SPI_Master.v:2.26-2.29" *)
  input clk;
  wire clk;
  (* src = "SPI_Master.v:12.5-12.23" *)
  reg communication_flag = 1'h1;
  (* src = "SPI_Master.v:18.9-18.14" *)
  reg [31:0] count = 32'd0;
  (* src = "SPI_Master.v:19.9-19.15" *)
  reg [31:0] countr = 32'd0;
  (* src = "SPI_Master.v:3.67-3.71" *)
  input cpha;
  wire cpha;
  (* src = "SPI_Master.v:3.54-3.58" *)
  input cpol;
  wire cpol;
  (* src = "SPI_Master.v:7.56-7.65" *)
  output [7:0] data_read;
  reg [7:0] data_read;
  (* src = "SPI_Master.v:2.67-2.80" *)
  input [7:0] data_to_write;
  wire [7:0] data_to_write;
  (* src = "SPI_Master.v:2.49-2.53" *)
  input load;
  wire load;
  (* src = "SPI_Master.v:10.5-10.12" *)
  reg sampled = 1'h1;
  (* src = "SPI_Master.v:11.5-11.13" *)
  reg sclk_old;
  (* src = "SPI_Master.v:3.32-3.45" *)
  input [1:0] slave_address;
  wire [1:0] slave_address;
  (* src = "SPI_Master.v:7.78-7.89" *)
  output slave_start;
  reg slave_start;
  (* src = "SPI_Master.v:2.37-2.42" *)
  input start;
  wire start;
  (* src = "SPI_Master.v:15.10-15.29" *)
  reg [7:0] transmission_buffer;
  (* src = "SPI_Master.v:17.9-17.30" *)
  reg [31:0] transmission_iterator = 32'd0;
  assign _078_ = $signed(_027_) + (* src = "SPI_Master.v:113.41-113.64" *) $signed(32'd1);
  assign _079_ = $signed(_076_) + (* src = "SPI_Master.v:120.33-120.41" *) $signed(32'd1);
  assign _080_ = $signed(_077_) + (* src = "SPI_Master.v:126.33-126.41" *) $signed(32'd1);
  assign _081_ = $signed(_053_) + (* src = "SPI_Master.v:136.41-136.64" *) $signed(32'd1);
  assign _082_ = $signed(_018_) + (* src = "SPI_Master.v:144.31-144.39" *) $signed(32'd1);
  assign _083_ = $signed(_019_) + (* src = "SPI_Master.v:149.33-149.41" *) $signed(32'd1);
  assign _084_ = $signed(_033_) + (* src = "SPI_Master.v:61.25-61.32" *) $signed(32'd1);
  assign _085_ = $signed(_034_) + (* src = "SPI_Master.v:72.10-72.18" *) $signed(32'd1);
  assign _086_ = $signed(_033_) + (* src = "SPI_Master.v:88.28-88.37" *) $signed(32'd1);
  assign _087_ = $signed(_033_) + (* src = "SPI_Master.v:97.28-97.35" *) $signed(32'd1);
  assign _088_ = _026_ & (* src = "SPI_Master.v:0.0-0.0" *) _117_;
  assign _089_ = _042_ & (* src = "SPI_Master.v:0.0-0.0" *) _118_;
  assign _090_ = _052_ & (* src = "SPI_Master.v:0.0-0.0" *) _119_;
  assign _091_ = data_read & (* src = "SPI_Master.v:0.0-0.0" *) _120_;
  assign _092_ = $signed(_048_) == (* src = "SPI_Master.v:111.20-111.30" *) $signed(32'd2);
  assign _093_ = ~ (* src = "SPI_Master.v:117.20-117.33" *) _036_;
  assign _094_ = ~ (* src = "SPI_Master.v:122.30-122.39" *) _032_;
  assign _095_ = $signed(_071_) == (* src = "SPI_Master.v:134.20-134.30" *) $signed(32'd2);
  assign _096_ = ~ (* src = "SPI_Master.v:140.20-140.33" *) _036_;
  assign _097_ = ~ (* src = "SPI_Master.v:146.38-146.47" *) _032_;
  assign _098_ = $signed(_047_) == (* src = "SPI_Master.v:155.4-155.13" *) $signed(32'd17);
  assign _099_ = $signed(count) == (* src = "SPI_Master.v:26.4-26.13" *) $signed(32'd17);
  assign _100_ = $signed(transmission_iterator) == (* src = "SPI_Master.v:32.4-32.28" *) $signed(32'd8);
  assign _101_ = ! (* src = "SPI_Master.v:58.12-58.20" *) $signed(_033_);
  assign _102_ = $signed(_033_) == (* src = "SPI_Master.v:79.20-79.28" *) $signed(32'd1);
  assign _103_ = _093_ && (* src = "SPI_Master.v:117.20-117.46" *) _032_;
  assign _104_ = _036_ && (* src = "SPI_Master.v:122.13-122.39" *) _094_;
  assign _105_ = _096_ && (* src = "SPI_Master.v:140.20-140.46" *) _032_;
  assign _106_ = _036_ && (* src = "SPI_Master.v:146.21-146.47" *) _097_;
  assign _107_ = _099_ && (* src = "SPI_Master.v:26.4-26.38" *) communication_flag;
  assign _108_ = start && (* src = "SPI_Master.v:38.4-38.31" *) communication_flag;
  assign _109_ = - (* src = "SPI_Master.v:0.0-0.0" *) $signed(_248_);
  assign _110_ = - (* src = "SPI_Master.v:0.0-0.0" *) $signed(_249_);
  assign _111_ = - (* src = "SPI_Master.v:0.0-0.0" *) $signed(_250_);
  assign _112_ = - (* src = "SPI_Master.v:0.0-0.0" *) $signed(_251_);
  assign _113_ = - (* src = "SPI_Master.v:0.0-0.0" *) $signed(_252_);
  assign _114_ = - (* src = "SPI_Master.v:0.0-0.0" *) $signed(_253_);
  assign _115_ = - (* src = "SPI_Master.v:0.0-0.0" *) $signed(_254_);
  assign _116_ = - (* src = "SPI_Master.v:0.0-0.0" *) $signed(_255_);
  assign _117_ = ~ (* src = "SPI_Master.v:0.0-0.0" *) _238_;
  assign _118_ = ~ (* src = "SPI_Master.v:0.0-0.0" *) _240_;
  assign _119_ = ~ (* src = "SPI_Master.v:0.0-0.0" *) _242_;
  assign _120_ = ~ (* src = "SPI_Master.v:0.0-0.0" *) _244_;
  assign _121_ = ~ (* src = "SPI_Master.v:78.24-78.29" *) SCLK;
  assign _122_ = _091_ | (* src = "SPI_Master.v:0.0-0.0" *) _245_;
  assign _123_ = _088_ | (* src = "SPI_Master.v:0.0-0.0" *) _239_;
  assign _124_ = _089_ | (* src = "SPI_Master.v:0.0-0.0" *) _241_;
  assign _125_ = _090_ | (* src = "SPI_Master.v:0.0-0.0" *) _243_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    SCLK <= _006_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    CS1 <= _002_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    CS2 <= _003_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    CS3 <= _004_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    MOSI <= _005_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    data_read <= _010_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    slave_start <= _013_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    sampled <= _011_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    sclk_old <= _012_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    communication_flag <= _007_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    CPOL <= _001_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    CPHA <= _000_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    transmission_buffer <= _014_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    transmission_iterator <= _015_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    count <= _008_;
  (* src = "SPI_Master.v:21.1-55.4" *)
  always @(posedge clk)
    countr <= _009_;
  assign _009_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) _034_ : _064_;
  assign _015_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) _027_ : _045_;
  assign _014_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) _026_ : _044_;
  assign _010_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) data_read : _035_;
  assign _005_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) MOSI : _046_;
  assign _008_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) _033_ : _047_;
  assign _012_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) sclk_old : _036_;
  assign _011_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) _024_ : _043_;
  assign _013_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) _037_ : _051_;
  assign _004_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) CS3 : _030_;
  assign _003_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) CS2 : _029_;
  assign _002_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) CS1 : _028_;
  assign _006_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) SCLK : _032_;
  assign _027_ = _108_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:38.4-38.31|SPI_Master.v:38.1-46.4" *) 32'd0 : transmission_iterator;
  assign _000_ = _108_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:38.4-38.31|SPI_Master.v:38.1-46.4" *) cpha : CPHA;
  assign _001_ = _108_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:38.4-38.31|SPI_Master.v:38.1-46.4" *) cpol : CPOL;
  assign _033_ = _108_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:38.4-38.31|SPI_Master.v:38.1-46.4" *) 32'd0 : _022_;
  assign _034_ = _108_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:38.4-38.31|SPI_Master.v:38.1-46.4" *) 32'd0 : _023_;
  assign _021_ = _108_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:38.4-38.31|SPI_Master.v:38.1-46.4" *) 1'h0 : communication_flag;
  assign _037_ = _100_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:32.4-32.28|SPI_Master.v:32.1-36.4" *) 1'h0 : _025_;
  assign _024_ = _100_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:32.4-32.28|SPI_Master.v:32.1-36.4" *) 1'h0 : sampled;
  assign _023_ = _107_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:26.4-26.38|SPI_Master.v:26.1-31.4" *) 32'd0 : countr;
  assign _022_ = _107_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:26.4-26.38|SPI_Master.v:26.1-31.4" *) 32'd0 : count;
  assign _025_ = _107_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:26.4-26.38|SPI_Master.v:26.1-31.4" *) 1'h0 : slave_start;
  assign _026_ = load ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:23.4-23.8|SPI_Master.v:23.1-24.37" *) data_to_write : transmission_buffer;
  assign _126_ = _098_ ? (* src = "SPI_Master.v:155.4-155.13|SPI_Master.v:155.1-158.4" *) 1'h1 : _021_;
  assign _007_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) _021_ : _126_;
  assign _127_ = _106_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:146.21-146.47|SPI_Master.v:146.17-150.20" *) _083_ : _019_;
  assign _128_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:132.5-132.10|SPI_Master.v:132.2-152.5" *) 32'hxxxxxxxx : _127_;
  assign _129_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _128_ : 32'hxxxxxxxx;
  assign _020_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _129_;
  assign _130_ = _106_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:146.21-146.47|SPI_Master.v:146.17-150.20" *) _246_ : _054_;
  assign _131_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:132.5-132.10|SPI_Master.v:132.2-152.5" *) 1'hx : _130_;
  assign _132_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _131_ : 1'hx;
  assign _075_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _132_;
  assign _133_ = _105_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:140.20-140.46|SPI_Master.v:140.17-145.20" *) _082_ : _018_;
  assign _134_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:132.5-132.10|SPI_Master.v:132.2-152.5" *) 32'hxxxxxxxx : _133_;
  assign _135_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _134_ : 32'hxxxxxxxx;
  assign _019_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _135_;
  assign _136_ = _105_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:140.20-140.46|SPI_Master.v:140.17-145.20" *) _125_ : _052_;
  assign _137_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:132.5-132.10|SPI_Master.v:132.2-152.5" *) 8'hxx : _136_;
  assign _138_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _137_ : 8'hxx;
  assign _073_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 8'hxx : _138_;
  assign _139_ = _105_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:140.20-140.46|SPI_Master.v:140.17-145.20" *) _124_ : _042_;
  assign _140_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:132.5-132.10|SPI_Master.v:132.2-152.5" *) 8'hxx : _139_;
  assign _141_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _140_ : 8'hxx;
  assign _065_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 8'hxx : _141_;
  assign _142_ = _095_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:134.20-134.30|SPI_Master.v:134.17-138.20" *) 32'd0 : _071_;
  assign _143_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:132.5-132.10|SPI_Master.v:132.2-152.5" *) 32'hxxxxxxxx : _142_;
  assign _144_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _143_ : 32'hxxxxxxxx;
  assign _018_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _144_;
  assign _145_ = _095_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:134.20-134.30|SPI_Master.v:134.17-138.20" *) _081_ : _053_;
  assign _146_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:132.5-132.10|SPI_Master.v:132.2-152.5" *) 32'hxxxxxxxx : _145_;
  assign _147_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _146_ : 32'hxxxxxxxx;
  assign _074_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _147_;
  assign _148_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:132.5-132.10|SPI_Master.v:132.2-152.5" *) _071_ : _020_;
  assign _149_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _148_ : 32'hxxxxxxxx;
  assign _017_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _149_;
  assign _150_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:132.5-132.10|SPI_Master.v:132.2-152.5" *) _054_ : _075_;
  assign _151_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _150_ : 1'hx;
  assign _070_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _151_;
  assign _152_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:132.5-132.10|SPI_Master.v:132.2-152.5" *) _052_ : _073_;
  assign _153_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _152_ : 8'hxx;
  assign _068_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 8'hxx : _153_;
  assign _154_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:132.5-132.10|SPI_Master.v:132.2-152.5" *) _042_ : _065_;
  assign _155_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _154_ : 8'hxx;
  assign _057_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 8'hxx : _155_;
  assign _156_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:132.5-132.10|SPI_Master.v:132.2-152.5" *) _053_ : _074_;
  assign _157_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _156_ : 32'hxxxxxxxx;
  assign _069_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _157_;
  assign _158_ = _104_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:122.13-122.39|SPI_Master.v:122.10-127.20" *) _080_ : _077_;
  assign _159_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:108.5-108.9|SPI_Master.v:108.2-129.5" *) _158_ : 32'hxxxxxxxx;
  assign _160_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _159_ : 32'hxxxxxxxx;
  assign _016_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _160_;
  assign _161_ = _104_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:122.13-122.39|SPI_Master.v:122.10-127.20" *) _123_ : _026_;
  assign _162_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:108.5-108.9|SPI_Master.v:108.2-129.5" *) _161_ : 8'hxx;
  assign _163_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _162_ : 8'hxx;
  assign _060_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 8'hxx : _163_;
  assign _164_ = _104_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:122.13-122.39|SPI_Master.v:122.10-127.20" *) _122_ : data_read;
  assign _165_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:108.5-108.9|SPI_Master.v:108.2-129.5" *) _164_ : 8'hxx;
  assign _166_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _165_ : 8'hxx;
  assign _049_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 8'hxx : _166_;
  assign _167_ = _103_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:117.20-117.46|SPI_Master.v:117.17-121.20" *) _079_ : _076_;
  assign _168_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:108.5-108.9|SPI_Master.v:108.2-129.5" *) _167_ : 32'hxxxxxxxx;
  assign _169_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _168_ : 32'hxxxxxxxx;
  assign _077_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _169_;
  assign _170_ = _103_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:117.20-117.46|SPI_Master.v:117.17-121.20" *) _247_ : _031_;
  assign _171_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:108.5-108.9|SPI_Master.v:108.2-129.5" *) _170_ : 1'hx;
  assign _172_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _171_ : 1'hx;
  assign _062_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _172_;
  assign _173_ = _092_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:111.20-111.30|SPI_Master.v:111.17-115.20" *) 32'd0 : _048_;
  assign _174_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:108.5-108.9|SPI_Master.v:108.2-129.5" *) _173_ : 32'hxxxxxxxx;
  assign _175_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _174_ : 32'hxxxxxxxx;
  assign _076_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _175_;
  assign _176_ = _092_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:111.20-111.30|SPI_Master.v:111.17-115.20" *) _078_ : _027_;
  assign _177_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:108.5-108.9|SPI_Master.v:108.2-129.5" *) _176_ : 32'hxxxxxxxx;
  assign _178_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _177_ : 32'hxxxxxxxx;
  assign _061_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _178_;
  assign _179_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:108.5-108.9|SPI_Master.v:108.2-129.5" *) _016_ : _048_;
  assign _180_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _179_ : 32'hxxxxxxxx;
  assign _071_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _180_;
  assign _181_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:108.5-108.9|SPI_Master.v:108.2-129.5" *) _060_ : _026_;
  assign _182_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _181_ : 8'hxx;
  assign _052_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 8'hxx : _182_;
  assign _183_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:108.5-108.9|SPI_Master.v:108.2-129.5" *) _049_ : data_read;
  assign _184_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _183_ : 8'hxx;
  assign _042_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 8'hxx : _184_;
  assign _185_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:108.5-108.9|SPI_Master.v:108.2-129.5" *) _062_ : _031_;
  assign _186_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _185_ : 1'hx;
  assign _054_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _186_;
  assign _187_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:108.5-108.9|SPI_Master.v:108.2-129.5" *) _061_ : _027_;
  assign _188_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _187_ : 32'hxxxxxxxx;
  assign _053_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _188_;
  assign _189_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _017_ : _048_;
  assign _064_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _189_;
  assign _190_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _069_ : _027_;
  assign _045_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _190_;
  assign _191_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _068_ : _026_;
  assign _044_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 8'hxx : _191_;
  assign _192_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _057_ : data_read;
  assign _035_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 8'hxx : _192_;
  assign _193_ = _043_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:106.4-106.14|SPI_Master.v:106.1-154.4" *) _070_ : _031_;
  assign _046_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _193_;
  assign _194_ = _024_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:92.23-92.33|SPI_Master.v:92.20-97.36" *) _037_ : 1'h1;
  assign _195_ = _102_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:79.20-79.28|SPI_Master.v:79.17-98.20" *) 1'hx : _194_;
  assign _196_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) 1'hx : _195_;
  assign _072_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _196_;
  assign _197_ = _024_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:92.23-92.33|SPI_Master.v:92.20-97.36" *) _024_ : 1'h1;
  assign _198_ = _102_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:79.20-79.28|SPI_Master.v:79.17-98.20" *) 1'hx : _197_;
  assign _199_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) 1'hx : _198_;
  assign _066_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _199_;
  assign _200_ = _024_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:92.23-92.33|SPI_Master.v:92.20-97.36" *) _087_ : _033_;
  assign _201_ = _102_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:79.20-79.28|SPI_Master.v:79.17-98.20" *) 32'hxxxxxxxx : _200_;
  assign _202_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) 32'hxxxxxxxx : _201_;
  assign _063_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _202_;
  assign _203_ = _001_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:81.23-81.30|SPI_Master.v:81.20-87.23" *) 1'h0 : 1'h1;
  assign _204_ = _102_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:79.20-79.28|SPI_Master.v:79.17-98.20" *) _203_ : 1'hx;
  assign _205_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) 1'hx : _204_;
  assign _058_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _205_;
  assign _206_ = _001_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:81.23-81.30|SPI_Master.v:81.20-87.23" *) _037_ : 1'h1;
  assign _207_ = _102_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:79.20-79.28|SPI_Master.v:79.17-98.20" *) _206_ : 1'hx;
  assign _208_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) 1'hx : _207_;
  assign _067_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _208_;
  assign _209_ = _102_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:79.20-79.28|SPI_Master.v:79.17-98.20" *) _086_ : _063_;
  assign _210_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) 32'hxxxxxxxx : _209_;
  assign _055_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _210_;
  assign _211_ = _102_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:79.20-79.28|SPI_Master.v:79.17-98.20" *) _058_ : _066_;
  assign _212_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) 1'hx : _211_;
  assign _050_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _212_;
  assign _213_ = _102_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:79.20-79.28|SPI_Master.v:79.17-98.20" *) _067_ : _072_;
  assign _214_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) 1'hx : _213_;
  assign _059_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _214_;
  assign _215_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:69.4-69.9|SPI_Master.v:69.1-73.4" *) _034_ : _085_;
  assign _216_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) _215_ : 32'hxxxxxxxx;
  assign _056_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _216_;
  assign _217_ = _000_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:69.4-69.9|SPI_Master.v:69.1-73.4" *) MOSI : _026_[0];
  assign _218_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) _217_ : 1'hx;
  assign _041_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _218_;
  assign _219_ = _220_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:0.0-0.0|SPI_Master.v:64.5-68.12" *) 1'h0 : 1'h1;
  assign _220_ = ! (* full_case = 32'd1 *) (* src = "SPI_Master.v:0.0-0.0|SPI_Master.v:64.5-68.12" *) slave_address;
  assign _221_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) _219_ : 1'hx;
  assign _038_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _221_;
  assign _222_ = _223_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:0.0-0.0|SPI_Master.v:64.5-68.12" *) 1'h0 : 1'h1;
  assign _223_ = slave_address == (* full_case = 32'd1 *) (* src = "SPI_Master.v:0.0-0.0|SPI_Master.v:64.5-68.12" *) 2'h2;
  assign _224_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) _222_ : 1'hx;
  assign _040_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _224_;
  assign _225_ = _226_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:0.0-0.0|SPI_Master.v:64.5-68.12" *) 1'h0 : 1'h1;
  assign _226_ = slave_address == (* full_case = 32'd1 *) (* src = "SPI_Master.v:0.0-0.0|SPI_Master.v:64.5-68.12" *) 2'h1;
  assign _227_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) _225_ : 1'hx;
  assign _039_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _227_;
  assign _228_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) _056_ : _034_;
  assign _048_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _228_;
  assign _229_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) _041_ : MOSI;
  assign _031_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _229_;
  assign _230_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) _040_ : CS3;
  assign _030_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _230_;
  assign _231_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) _039_ : CS2;
  assign _029_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _231_;
  assign _232_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) _038_ : CS1;
  assign _028_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _232_;
  assign _233_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) 1'h0 : _050_;
  assign _043_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _233_;
  assign _234_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) _084_ : _055_;
  assign _047_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 32'hxxxxxxxx : _234_;
  assign _235_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) _001_ : _121_;
  assign _032_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _235_;
  assign _236_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) sclk_old : SCLK;
  assign _036_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _236_;
  assign _237_ = _101_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:58.12-58.20|SPI_Master.v:58.9-99.12" *) _037_ : _059_;
  assign _051_ = _021_ ? (* full_case = 32'd1 *) (* src = "SPI_Master.v:47.4-47.23|SPI_Master.v:47.1-54.4" *) 1'hx : _237_;
  assign _238_ = $signed(_109_) < 0 ? 1'h1 << - _109_ : 1'h1 >> _109_;
  assign _239_ = $signed(_110_) < 0 ? MISO << - _110_ : MISO >> _110_;
  assign _240_ = $signed(_111_) < 0 ? 1'h1 << - _111_ : 1'h1 >> _111_;
  assign _241_ = $signed(_112_) < 0 ? MISO << - _112_ : MISO >> _112_;
  assign _242_ = $signed(_113_) < 0 ? 1'h1 << - _113_ : 1'h1 >> _113_;
  assign _243_ = $signed(_114_) < 0 ? MISO << - _114_ : MISO >> _114_;
  assign _244_ = $signed(_115_) < 0 ? 1'h1 << - _115_ : 1'h1 >> _115_;
  assign _245_ = $signed(_116_) < 0 ? MISO << - _116_ : MISO >> _116_;
  wire [7:0] _528_ = _073_;
  assign _246_ = _528_[$signed(_074_) +: 1];
  wire [7:0] _529_ = _026_;
  assign _247_ = _529_[$signed(_061_) +: 1];
  assign _248_ = $signed({ _061_[31], _061_ }) - (* src = "SPI_Master.v:0.0-0.0" *) $signed(32'd0);
  assign _249_ = $signed({ _061_[31], _061_ }) - (* src = "SPI_Master.v:0.0-0.0" *) $signed(32'd0);
  assign _250_ = $signed({ _074_[31], _074_ }) - (* src = "SPI_Master.v:0.0-0.0" *) $signed(32'd0);
  assign _251_ = $signed({ _074_[31], _074_ }) - (* src = "SPI_Master.v:0.0-0.0" *) $signed(32'd0);
  assign _252_ = $signed({ _074_[31], _074_ }) - (* src = "SPI_Master.v:0.0-0.0" *) $signed(32'd0);
  assign _253_ = $signed({ _074_[31], _074_ }) - (* src = "SPI_Master.v:0.0-0.0" *) $signed(32'd0);
  assign _254_ = $signed({ _061_[31], _061_ }) - (* src = "SPI_Master.v:0.0-0.0" *) $signed(32'd0);
  assign _255_ = $signed({ _061_[31], _061_ }) - (* src = "SPI_Master.v:0.0-0.0" *) $signed(32'd0);
endmodule
