/* Generated by Yosys 0.20 (git sha1 4fcb95ed087, clang  -fPIC -Os) */

(* src = "dffsr.v:1.1-29.10" *)
module m_0(CLK, SET, CLR, D, Q);
  (* src = "dffsr.v:8.7-8.10" *)
  input CLK;
  wire CLK;
  (* src = "dffsr.v:9.24-9.27" *)
  input CLR;
  wire CLR;
  (* src = "dffsr.v:9.29-9.30" *)
  input D;
  wire D;
  (* src = "dffsr.v:10.24-10.25" *)
  output Q;
  reg Q;
  (* src = "dffsr.v:9.19-9.22" *)
  input SET;
  wire SET;
  (* src = "dffsr.v:19.3-25.18" *)
  always @(posedge CLK, posedge SET, posedge CLR)
    if (CLR) Q <= 1'b0;
    else if (SET) Q <= 1'b1;
    else Q <= D;
endmodule
