/* Generated by Yosys 0.20 (git sha1 4fcb95ed087, clang  -fPIC -Os) */

(* dynports =  1  *)
(* src = "dffsre.v:1.1-30.10" *)
module m_0(CLK, SET, CLR, EN, D, Q);
  (* src = "dffsre.v:9.7-9.10" *)
  input CLK;
  wire CLK;
  (* src = "dffsre.v:10.24-10.27" *)
  input CLR;
  wire CLR;
  (* src = "dffsre.v:10.29-10.30" *)
  input D;
  wire D;
  (* src = "dffsre.v:9.12-9.14" *)
  input EN;
  wire EN;
  (* src = "dffsre.v:11.24-11.25" *)
  output Q;
  reg Q;
  (* src = "dffsre.v:10.19-10.22" *)
  input SET;
  wire SET;
  (* src = "dffsre.v:20.3-26.18" *)
  always @(posedge CLK, posedge SET, posedge CLR)
    if (CLR) Q <= 1'b0;
    else if (SET) Q <= 1'b1;
    else if (EN) Q <= D;
endmodule
