/* Generated by Yosys 0.20 (git sha1 4fcb95ed087, clang  -fPIC -Os) */

(* dynports =  1  *)
(* src = "dlatch.v:1.1-15.10" *)
module m_0(CLR, D, EN, Q, SET);
  (* src = "dlatch.v:7.19-7.20" *)
  input CLR;
  wire CLR;
  (* src = "dlatch.v:7.19-7.20" *)
  input D;
  wire D;
  (* src = "dlatch.v:6.7-6.9" *)
  input EN;
  wire EN;
  (* src = "dlatch.v:8.24-8.25" *)
  output Q;
  reg Q;
  (* src = "dlatch.v:7.19-7.20" *)
  input SET;
  wire SET;
  (* src = "dlatch.v:10.1-13.4" *)
  always @*
    if (CLR) Q = 1'b0;
    else if (SET) Q = 1'b1;
    else if (EN) Q = D;
endmodule
