/* Generated by Yosys 0.20 (git sha1 4fcb95ed087, clang  -fPIC -Os) */

(* dynports =  1  *)
(* src = "dlatch.v:1.1-15.10" *)
module m_0(CLR,CLR_t,SET, SET_t, Q, Q_t);
  (* src = "dlatch.v:7.19-7.20" *)
  input [1:0] CLR;
  wire [1:0] CLR;
  (* src = "dlatch.v:8.24-8.25" *)
  output [1:0] Q;
  reg [1:0] Q;
  (* src = "dlatch.v:6.7-6.9" *)
  input [1:0] SET;
  wire [1:0] SET;
  
  input wire [31:0] CLR_t;
  input wire [31:0] SET_t;
  output reg [31:0] Q_t = 0;
  (* src = "dlatch.v:10.1-13.4" *)
  always @*
    if (CLR[0])begin
     Q[0] <= 1'b0;
     Q_t <= CLR_t;
     end
    else if (SET[0])begin
     Q[0] <= 1'b1;
     Q_t <= SET_t;
     end
  (* src = "dlatch.v:10.1-13.4" *)
  always @*
    if (CLR[1])begin
     Q[1] <= 1'b0;
     Q_t <= CLR_t;
     end
    else if (SET[1])begin
     Q[1] <= 1'b1;
     Q_t <= SET_t;
     end
endmodule
