/* Generated by Yosys 0.20 (git sha1 4fcb95ed087, clang  -fPIC -Os) */

(* dynports =  1  *)
(* src = "shiftx.v:1.1-22.10" *)
module m_0(A, B, Y);
  (* src = "shiftx.v:9.25-9.26" *)
  input [1:0] A;
  wire [1:0] A;
  (* src = "shiftx.v:10.25-10.26" *)
  input [1:0] B;
  wire [1:0] B;
  (* src = "shiftx.v:11.26-11.27" *)
  output [1:0] Y;
  wire [1:0] Y;
  wire [1:0] _1_ = A;
  assign Y = _1_[B +: 2];
endmodule
