/* Generated by Yosys 0.20 (git sha1 4fcb95ed087, clang 14.0.0-1ubuntu1 -fPIC -Os) */

(* dynports =  1  *)
(* src = "dlatchsr.v:1.1-15.10" *)
module m_0(CLR, D, EN, Q, SET);
  (* src = "dlatchsr.v:7.19-7.20" *)
  input [1:0] CLR;
  wire [1:0] CLR;
  (* src = "dlatchsr.v:7.19-7.20" *)
  input [1:0] D;
  wire [1:0] D;
  (* src = "dlatchsr.v:6.7-6.9" *)
  input EN;
  wire EN;
  (* src = "dlatchsr.v:8.24-8.25" *)
  output [1:0] Q;
  reg [1:0] Q;
  (* src = "dlatchsr.v:7.19-7.20" *)
  input [1:0] SET;
  wire [1:0] SET;
  (* src = "dlatchsr.v:10.1-13.4" *)
  always @*
    if (CLR[0]) Q[0] = 1'b0;
    else if (SET[0]) Q[0] = 1'b1;
    else if (EN) Q[0] = D[0];
  (* src = "dlatchsr.v:10.1-13.4" *)
  always @*
    if (CLR[1]) Q[1] = 1'b0;
    else if (SET[1]) Q[1] = 1'b1;
    else if (EN) Q[1] = D[1];
endmodule
