/* Generated by Yosys 0.36 (git sha1 8f07a0d8404, clang 16.0.6 -fPIC -Os) */

(* top =  1  *)
(* src = "SPI_Slave.v:1.1-68.10" *)
module SPI_Slave(reset, In_Data, slaveCPOL, slaveCPHA, slaveSCLK, slaveCS_, slaveMISO, slaveMOSI, slave_start, read_data);
  wire _00_;
  wire _01_;
  wire _02_;
  (* src = "SPI_Slave.v:42.10-42.34" *)
  wire _03_;
  (* src = "SPI_Slave.v:42.37-42.61" *)
  wire _04_;
  (* src = "SPI_Slave.v:45.37-45.61" *)
  wire _05_;
  (* src = "SPI_Slave.v:45.10-45.34" *)
  wire _06_;
  (* src = "SPI_Slave.v:42.10-42.61" *)
  wire _07_;
  (* src = "SPI_Slave.v:45.10-45.61" *)
  wire _08_;
  (* src = "SPI_Slave.v:15.18-15.25" *)
  input [7:0] In_Data;
  wire [7:0] In_Data;
  (* src = "SPI_Slave.v:25.11-25.17" *)
  reg [7:0] memReg;
  (* src = "SPI_Slave.v:23.19-23.28" *)
  output [7:0] read_data;
  wire [7:0] read_data;
  (* src = "SPI_Slave.v:16.12-16.17" *)
  input reset;
  wire reset;
  (* src = "SPI_Slave.v:17.34-17.43" *)
  input slaveCPHA;
  wire slaveCPHA;
  (* src = "SPI_Slave.v:17.23-17.32" *)
  input slaveCPOL;
  wire slaveCPOL;
  (* src = "SPI_Slave.v:18.12-18.20" *)
  input slaveCS_;
  wire slaveCS_;
  (* src = "SPI_Slave.v:22.12-22.21" *)
  output slaveMISO;
  reg slaveMISO;
  (* src = "SPI_Slave.v:19.12-19.21" *)
  input slaveMOSI;
  wire slaveMOSI;
  (* src = "SPI_Slave.v:17.12-17.21" *)
  input slaveSCLK;
  wire slaveSCLK;
  (* src = "SPI_Slave.v:20.12-20.23" *)
  input slave_start;
  wire slave_start;
  (* src = "SPI_Slave.v:36.1-51.4" *)
  always @(negedge slaveSCLK)
    if (_01_) slaveMISO <= memReg[0];
  (* src = "SPI_Slave.v:52.1-65.4" *)
  always @(posedge slaveSCLK)
    if (_00_) slaveMISO <= memReg[0];
  (* src = "SPI_Slave.v:52.1-65.4" *)
  always @(posedge slaveSCLK)
    if (_01_) memReg <= { slaveMOSI, memReg[7:1] };
  (* src = "SPI_Slave.v:36.1-51.4" *)
  always @(negedge slaveSCLK)
    if (_00_) memReg <= { slaveMOSI, memReg[7:1] };
  assign _02_ = ~ slaveCS_;
  assign _00_ = & { _02_, _08_, slave_start };
  assign _01_ = & { _02_, _07_, slave_start };
  assign _06_ = { slaveCPOL, slaveCPHA } == (* src = "SPI_Slave.v:59.9-59.33" *) 2'h1;
  assign _05_ = { slaveCPOL, slaveCPHA } == (* src = "SPI_Slave.v:59.36-59.60" *) 2'h3;
  assign _03_ = ! (* src = "SPI_Slave.v:61.9-61.33" *) { slaveCPOL, slaveCPHA };
  assign _04_ = { slaveCPOL, slaveCPHA } == (* src = "SPI_Slave.v:61.36-61.60" *) 2'h2;
  assign _08_ = _06_ || (* src = "SPI_Slave.v:59.9-59.60" *) _05_;
  assign _07_ = _03_ || (* src = "SPI_Slave.v:61.9-61.60" *) _04_;
  (* src = "SPI_Slave.v:33.1-34.24" *)
  always @(negedge slaveCS_)
    slaveMISO <= memReg[0];
  (* src = "SPI_Slave.v:28.1-31.4" *)
  always @(posedge reset)
    memReg <= In_Data;
  assign read_data = memReg;
endmodule
