/* Generated by Yosys 0.20 (git sha1 4fcb95ed087, clang  -fPIC -Os) */

(* dynports =  1  *)
(* src = "dlatch.v:1.1-15.10" *)
module m_0(CLK, SET, CLR, EN, D, Q);
  (* src = "dlatch.v:6.7-6.9" *)
  input CLK;
  wire CLK;
  (* src = "dlatch.v:7.19-7.20" *)
  input [1:0] CLR;
  wire [1:0] CLR;
  (* src = "dlatch.v:7.19-7.20" *)
  input [1:0] D;
  wire [1:0] D;
  (* src = "dlatch.v:7.19-7.20" *)
  input EN;
  wire EN;
  (* src = "dlatch.v:8.24-8.25" *)
  output [1:0] Q;
  reg [1:0] Q;
  (* src = "dlatch.v:7.19-7.20" *)
  input [1:0] SET;
  wire [1:0] SET;
  (* src = "dlatch.v:10.1-13.4" *)
  always @(posedge CLK, posedge SET[0], posedge CLR[0])
    if (CLR[0]) Q[0] <= 1'b0;
    else if (SET[0]) Q[0] <= 1'b1;
    else if (EN) Q[0] <= D[0];
  (* src = "dlatch.v:10.1-13.4" *)
  always @(posedge CLK, posedge SET[1], posedge CLR[1])
    if (CLR[1]) Q[1] <= 1'b0;
    else if (SET[1]) Q[1] <= 1'b1;
    else if (EN) Q[1] <= D[1];
endmodule
