/* Generated by Yosys 0.20 (git sha1 4fcb95ed087, clang  -fPIC -Os) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "shift.v:1.1-29.10" *)
module m_0(A,A_t, B,B_t, Y,Y_t);
  (* src = "shift.v:24.28-24.34" *)
  wire [1:0] _0_;
  (* src = "shift.v:9.25-9.26" *)
  input [1:0] A;
  wire [1:0] A;
  (* src = "shift.v:10.25-10.26" *)
  input [1:0] B;
  wire [1:0] B;
  (* src = "shift.v:11.26-11.27" *)
  output [1:0] Y;
  wire [1:0] Y;
  
  input wire [31:0] A_t;
  input wire [31:0] B_t;
  output wire [31:0] Y_t;
  assign Y = $signed(B) < 0 ? A << - B : A >> B;
  assign _0_[1] = Y[1];
  assign _0_[0] = Y[0];
  assign Y_t = A_t | B_t;
endmodule
