/* Generated by Yosys 0.48+70 (git sha1 6225abec7, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* keep =  1  *)
(* src = "EX_stage.v:13.1-59.10" *)
module EX_stage(clk, rst, pipeline_reg_in, pipeline_reg_out, ex_op_dest);
  (* src = "EX_stage.v:46.2-54.5" *)
  wire [37:0] _0_;
  wire [15:0] _1_;
  wire _2_;
  wire [21:0] _3_;
  wire _4_;
  (* src = "EX_stage.v:30.14-30.21" *)
  wire [2:0] alu_cmd;
  (* src = "EX_stage.v:31.15-31.23" *)
  wire [15:0] alu_src1;
  (* src = "EX_stage.v:32.15-32.23" *)
  wire [15:0] alu_src2;
  (* src = "EX_stage.v:15.12-15.15" *)
  input clk;
  wire clk;
  (* src = "EX_stage.v:34.15-34.28" *)
  wire [15:0] ex_alu_result;
  (* src = "EX_stage.v:28.17-28.27" *)
  output [2:0] ex_op_dest;
  wire [2:0] ex_op_dest;
  (* src = "EX_stage.v:18.17-18.32" *)
  input [56:0] pipeline_reg_in;
  wire [56:0] pipeline_reg_in;
  (* src = "EX_stage.v:23.21-23.37" *)
  output [37:0] pipeline_reg_out;
  reg [37:0] pipeline_reg_out;
  (* src = "EX_stage.v:16.12-16.15" *)
  input rst;
  wire rst;
  (* src = "EX_stage.v:46.2-54.5" *)
  always @(posedge clk)
    pipeline_reg_out <= { _1_, _3_ };
  assign _1_ = _2_ ? (* full_case = 32'd1 *) (* src = "EX_stage.v:47.6-47.9|EX_stage.v:47.3-53.6" *) 16'h0000 : ex_alu_result;
  assign _3_ = _4_ ? (* full_case = 32'd1 *) (* src = "EX_stage.v:47.6-47.9|EX_stage.v:47.3-53.6" *) 22'h000000 : pipeline_reg_in[21:0];
  (* module_not_derived = 32'd1 *)
  (* src = "EX_stage.v:37.6-42.3" *)
  alu alu_inst (
    .a(alu_src1),
    .b(alu_src2),
    .cmd(alu_cmd),
    .r(ex_alu_result)
  );
  assign alu_cmd = pipeline_reg_in[56:54];
  assign alu_src1 = pipeline_reg_in[53:38];
  assign alu_src2 = pipeline_reg_in[37:22];
  assign ex_op_dest = pipeline_reg_in[3:1];
  assign _2_ = rst;
  assign _0_[37:22] = _1_;
  assign _4_ = rst;
  assign _0_[21:0] = _3_;
endmodule

(* keep =  1  *)
(* src = "ID_stage.v:14.1-291.10" *)
module ID_stage(clk, rst, instruction_decode_en, pipeline_reg_out, instruction, branch_offset_imm, branch_taken, reg_read_addr_1, reg_read_addr_2, reg_read_data_1, reg_read_data_2, decoding_op_src1, decoding_op_src2);
  (* src = "ID_stage.v:99.2-212.5" *)
  wire _000_;
  (* src = "ID_stage.v:253.2-277.5" *)
  wire _001_;
  (* src = "ID_stage.v:99.2-212.5" *)
  wire [2:0] _002_;
  (* src = "ID_stage.v:75.2-84.5" *)
  wire [15:0] _003_;
  (* src = "ID_stage.v:229.2-245.5" *)
  wire [56:0] _004_;
  (* src = "ID_stage.v:99.2-212.5" *)
  wire _005_;
  (* src = "ID_stage.v:99.2-212.5" *)
  wire _006_;
  (* src = "ID_stage.v:99.2-212.5" *)
  wire _007_;
  (* src = "ID_stage.v:253.2-277.5" *)
  wire _008_;
  (* src = "ID_stage.v:99.2-212.5" *)
  wire [2:0] _009_;
  (* src = "ID_stage.v:99.2-212.5" *)
  wire _010_;
  (* src = "ID_stage.v:99.2-212.5" *)
  wire _011_;
  (* src = "ID_stage.v:99.2-212.5" *)
  wire _012_;
  (* src = "ID_stage.v:253.2-277.5" *)
  wire _013_;
  (* src = "ID_stage.v:99.2-212.5" *)
  wire [2:0] _014_;
  (* src = "ID_stage.v:99.2-212.5" *)
  wire _015_;
  (* src = "ID_stage.v:99.2-212.5" *)
  wire _016_;
  (* src = "ID_stage.v:253.2-277.5" *)
  wire _017_;
  wire _018_;
  wire _019_;
  (* src = "ID_stage.v:206.7-206.74" *)
  wire _020_;
  (* src = "ID_stage.v:268.7-268.128" *)
  wire _021_;
  (* src = "ID_stage.v:214.35-214.56" *)
  wire _022_;
  (* src = "ID_stage.v:215.34-215.55" *)
  wire _023_;
  (* src = "ID_stage.v:258.10-258.30" *)
  wire _024_;
  (* src = "ID_stage.v:284.6-284.27" *)
  wire _025_;
  (* src = "ID_stage.v:285.6-285.27" *)
  wire _026_;
  (* src = "ID_stage.v:286.6-286.27" *)
  wire _027_;
  (* src = "ID_stage.v:287.6-287.27" *)
  wire _028_;
  (* src = "ID_stage.v:93.34-93.76" *)
  wire [31:0] _029_;
  (* src = "ID_stage.v:96.31-96.70" *)
  wire [31:0] _030_;
  (* src = "ID_stage.v:284.6-285.27" *)
  wire _031_;
  (* src = "ID_stage.v:284.6-286.27" *)
  wire _032_;
  (* src = "ID_stage.v:284.6-287.27" *)
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire [2:0] _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire [2:0] _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire [2:0] _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire [15:0] _128_;
  wire _129_;
  (* src = "ID_stage.v:214.33-214.65" *)
  wire [31:0] _130_;
  (* src = "ID_stage.v:215.32-215.64" *)
  wire [31:0] _131_;
  (* src = "ID_stage.v:222.23-222.81" *)
  wire [15:0] _132_;
  (* src = "ID_stage.v:283.28-289.22" *)
  wire [2:0] _133_;
  (* src = "ID_stage.v:88.19-88.90" *)
  wire [2:0] _134_;
  (* src = "ID_stage.v:93.34-93.76" *)
  wire [31:0] _135_;
  (* src = "ID_stage.v:96.31-96.70" *)
  wire [31:0] _136_;
  (* src = "ID_stage.v:66.10-66.22" *)
  wire alu_src2_mux;
  (* src = "ID_stage.v:29.17-29.34" *)
  output [5:0] branch_offset_imm;
  wire [5:0] branch_offset_imm;
  (* src = "ID_stage.v:30.16-30.28" *)
  output branch_taken;
  wire branch_taken;
  (* src = "ID_stage.v:16.12-16.15" *)
  input clk;
  wire clk;
  (* src = "ID_stage.v:67.10-67.31" *)
  wire decoding_op_is_branch;
  (* src = "ID_stage.v:68.10-68.30" *)
  wire decoding_op_is_store;
  (* src = "ID_stage.v:39.17-39.33" *)
  output [2:0] decoding_op_src1;
  wire [2:0] decoding_op_src1;
  (* src = "ID_stage.v:40.17-40.33" *)
  output [2:0] decoding_op_src2;
  wire [2:0] decoding_op_src2;
  (* src = "ID_stage.v:62.14-62.24" *)
  wire [2:0] ex_alu_cmd;
  (* src = "ID_stage.v:63.15-63.26" *)
  wire [15:0] ex_alu_src1;
  (* src = "ID_stage.v:64.15-64.26" *)
  wire [15:0] ex_alu_src2;
  (* src = "ID_stage.v:28.17-28.28" *)
  input [15:0] instruction;
  wire [15:0] instruction;
  (* src = "ID_stage.v:18.12-18.33" *)
  input instruction_decode_en;
  wire instruction_decode_en;
  (* src = "ID_stage.v:46.15-46.30" *)
  reg [15:0] instruction_reg;
  (* src = "ID_stage.v:48.14-48.21" *)
  wire [2:0] ir_dest;
  (* src = "ID_stage.v:70.14-70.33" *)
  wire [2:0] ir_dest_with_bubble;
  (* src = "ID_stage.v:51.14-51.20" *)
  wire [5:0] ir_imm;
  (* src = "ID_stage.v:47.14-47.24" *)
  wire [3:0] ir_op_code;
  (* src = "ID_stage.v:69.14-69.36" *)
  wire [3:0] ir_op_code_with_bubble;
  (* src = "ID_stage.v:49.14-49.21" *)
  wire [2:0] ir_src1;
  (* src = "ID_stage.v:50.14-50.21" *)
  wire [2:0] ir_src2;
  (* src = "ID_stage.v:60.15-60.29" *)
  wire [15:0] mem_write_data;
  (* src = "ID_stage.v:59.10-59.22" *)
  wire mem_write_en;
  (* src = "ID_stage.v:23.21-23.37" *)
  output [56:0] pipeline_reg_out;
  reg [56:0] pipeline_reg_out;
  (* src = "ID_stage.v:33.17-33.32" *)
  output [2:0] reg_read_addr_1;
  wire [2:0] reg_read_addr_1;
  (* src = "ID_stage.v:34.17-34.32" *)
  output [2:0] reg_read_addr_2;
  wire [2:0] reg_read_addr_2;
  (* src = "ID_stage.v:35.17-35.32" *)
  input [15:0] reg_read_data_1;
  wire [15:0] reg_read_data_1;
  (* src = "ID_stage.v:36.17-36.32" *)
  input [15:0] reg_read_data_2;
  wire [15:0] reg_read_data_2;
  (* src = "ID_stage.v:17.12-17.15" *)
  input rst;
  wire rst;
  (* src = "ID_stage.v:56.14-56.29" *)
  wire [2:0] write_back_dest;
  (* src = "ID_stage.v:55.10-55.23" *)
  wire write_back_en;
  (* src = "ID_stage.v:57.10-57.31" *)
  wire write_back_result_mux;
  always @*
    if (_020_)
      $write("ERROR: Unknown Instruction: %04b\n", $unsigned(ir_op_code_with_bubble));
  always @*
    if (_021_)
      $write("ERROR: Unknown branch condition %03b, in branch instruction %04b \n\n", $unsigned(ir_dest_with_bubble), $unsigned(ir_op_code_with_bubble));
  assign _022_ = ir_op_code == (* src = "ID_stage.v:214.35-214.56" *) 4'hc;
  assign _023_ = ir_op_code == (* src = "ID_stage.v:215.34-215.55" *) 4'hb;
  assign _024_ = ! (* src = "ID_stage.v:258.10-258.30" *) reg_read_data_1;
  assign _025_ = ! (* src = "ID_stage.v:284.6-284.27" *) ir_op_code;
  assign _026_ = ir_op_code == (* src = "ID_stage.v:285.6-285.27" *) 4'h9;
  assign _027_ = ir_op_code == (* src = "ID_stage.v:286.6-286.27" *) 4'ha;
  assign _028_ = ir_op_code == (* src = "ID_stage.v:287.6-287.27" *) 4'hc;
  assign _029_ = + (* src = "ID_stage.v:93.34-93.76" *) ir_op_code;
  assign _030_ = + (* src = "ID_stage.v:96.31-96.70" *) ir_dest;
  assign _031_ = _025_ || (* src = "ID_stage.v:284.6-285.27" *) _026_;
  assign _032_ = _031_ || (* src = "ID_stage.v:284.6-286.27" *) _027_;
  assign _033_ = _032_ || (* src = "ID_stage.v:284.6-287.27" *) _028_;
  (* src = "ID_stage.v:229.2-245.5" *)
  always @(posedge clk, posedge _018_)
    if (_018_) pipeline_reg_out <= 57'h000000000000000;
    else pipeline_reg_out <= { _106_, reg_read_data_1, _132_, _131_[0], reg_read_data_2, _110_, _136_[2:0], _108_ };
  (* src = "ID_stage.v:75.2-84.5" *)
  always @(posedge clk, posedge _019_)
    if (_019_) instruction_reg <= 16'h0000;
    else instruction_reg <= _128_;
  assign _034_ = _035_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:258.10-258.30|ID_stage.v:258.7-261.25" *) 1'h1 : 1'h0;
  assign _036_ = _037_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:255.4-272.11" *) _034_ : 1'hx;
  assign _037_ = ! (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:255.4-272.11" *) ir_dest_with_bubble;
  assign _038_ = _039_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:254.6-254.27|ID_stage.v:254.3-276.6" *) _036_ : 1'hx;
  assign _040_ = _041_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:255.4-272.11" *) _017_ : 1'h0;
  assign _041_ = ! (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:255.4-272.11" *) ir_dest_with_bubble;
  assign _042_ = _043_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:254.6-254.27|ID_stage.v:254.3-276.6" *) _040_ : 1'hx;
  assign _044_ = _045_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:254.6-254.27|ID_stage.v:254.3-276.6" *) _013_ : 1'h0;
  assign _046_ = _047_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:255.4-272.11" *) 1'h0 : 1'h1;
  assign _047_ = ! (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:255.4-272.11" *) ir_dest_with_bubble;
  assign _048_ = _049_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:254.6-254.27|ID_stage.v:254.3-276.6" *) _046_ : 1'h0;
  function [0:0] _164_;
    input [0:0] a;
    input [10:0] b;
    input [10:0] s;
    (* full_case = 32'd1 *)
    (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *)
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        _164_ = b[0:0];
      11'b?????????1?:
        _164_ = b[1:1];
      11'b????????1??:
        _164_ = b[2:2];
      11'b???????1???:
        _164_ = b[3:3];
      11'b??????1????:
        _164_ = b[4:4];
      11'b?????1?????:
        _164_ = b[5:5];
      11'b????1??????:
        _164_ = b[6:6];
      11'b???1???????:
        _164_ = b[7:7];
      11'b??1????????:
        _164_ = b[8:8];
      11'b?1?????????:
        _164_ = b[9:9];
      11'b1??????????:
        _164_ = b[10:10];
      default:
        _164_ = a;
    endcase
  endfunction
  assign _050_ = _164_(1'hx, 11'h00f, { _061_, _060_, _059_, _058_, _057_, _056_, _055_, _054_, _053_, _052_, _051_ });
  assign _051_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'hc;
  assign _052_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'hb;
  assign _053_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'ha;
  assign _054_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h9;
  assign _055_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h8;
  assign _056_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h7;
  assign _057_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h6;
  assign _058_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h4;
  assign _059_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h3;
  assign _060_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h2;
  assign _061_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h1;
  assign _062_ = _063_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:100.6-100.9|ID_stage.v:100.3-211.6" *) 1'hx : _050_;
  function [2:0] _177_;
    input [2:0] a;
    input [32:0] b;
    input [10:0] s;
    (* full_case = 32'd1 *)
    (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *)
    (* parallel_case *)
    casez (s)
      11'b??????????1:
        _177_ = b[2:0];
      11'b?????????1?:
        _177_ = b[5:3];
      11'b????????1??:
        _177_ = b[8:6];
      11'b???????1???:
        _177_ = b[11:9];
      11'b??????1????:
        _177_ = b[14:12];
      11'b?????1?????:
        _177_ = b[17:15];
      11'b????1??????:
        _177_ = b[20:18];
      11'b???1???????:
        _177_ = b[23:21];
      11'b??1????????:
        _177_ = b[26:24];
      11'b?1?????????:
        _177_ = b[29:27];
      11'b1??????????:
        _177_ = b[32:30];
      default:
        _177_ = a;
    endcase
  endfunction
  assign _064_ = _177_(3'hx, 33'h00a72ee00, { _075_, _074_, _073_, _072_, _071_, _070_, _069_, _068_, _067_, _066_, _065_ });
  assign _065_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'hb;
  assign _066_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'ha;
  assign _067_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h9;
  assign _068_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h8;
  assign _069_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h7;
  assign _070_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h6;
  assign _071_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h5;
  assign _072_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h4;
  assign _073_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h3;
  assign _074_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h2;
  assign _075_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h1;
  assign _076_ = _077_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:100.6-100.9|ID_stage.v:100.3-211.6" *) 3'hx : _064_;
  function [0:0] _190_;
    input [0:0] a;
    input [9:0] b;
    input [9:0] s;
    (* full_case = 32'd1 *)
    (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *)
    (* parallel_case *)
    casez (s)
      10'b?????????1:
        _190_ = b[0:0];
      10'b????????1?:
        _190_ = b[1:1];
      10'b???????1??:
        _190_ = b[2:2];
      10'b??????1???:
        _190_ = b[3:3];
      10'b?????1????:
        _190_ = b[4:4];
      10'b????1?????:
        _190_ = b[5:5];
      10'b???1??????:
        _190_ = b[6:6];
      10'b??1???????:
        _190_ = b[7:7];
      10'b?1????????:
        _190_ = b[8:8];
      10'b1?????????:
        _190_ = b[9:9];
      default:
        _190_ = a;
    endcase
  endfunction
  assign _078_ = _190_(1'hx, 10'h001, { _088_, _087_, _086_, _085_, _084_, _083_, _082_, _081_, _080_, _079_ });
  assign _079_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'ha;
  assign _080_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h9;
  assign _081_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h8;
  assign _082_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h7;
  assign _083_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h6;
  assign _084_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h5;
  assign _085_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h4;
  assign _086_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h3;
  assign _087_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h2;
  assign _088_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h1;
  assign _089_ = _090_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:100.6-100.9|ID_stage.v:100.3-211.6" *) 1'hx : _078_;
  function [0:0] _202_;
    input [0:0] a;
    input [9:0] b;
    input [9:0] s;
    (* full_case = 32'd1 *)
    (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *)
    (* parallel_case *)
    casez (s)
      10'b?????????1:
        _202_ = b[0:0];
      10'b????????1?:
        _202_ = b[1:1];
      10'b???????1??:
        _202_ = b[2:2];
      10'b??????1???:
        _202_ = b[3:3];
      10'b?????1????:
        _202_ = b[4:4];
      10'b????1?????:
        _202_ = b[5:5];
      10'b???1??????:
        _202_ = b[6:6];
      10'b??1???????:
        _202_ = b[7:7];
      10'b?1????????:
        _202_ = b[8:8];
      10'b1?????????:
        _202_ = b[9:9];
      default:
        _202_ = a;
    endcase
  endfunction
  assign _091_ = _202_(1'h0, 10'h3ff, { _101_, _100_, _099_, _098_, _097_, _096_, _095_, _094_, _093_, _092_ });
  assign _092_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'ha;
  assign _093_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h9;
  assign _094_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h8;
  assign _095_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h7;
  assign _096_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h6;
  assign _097_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h5;
  assign _098_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h4;
  assign _099_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h3;
  assign _100_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h2;
  assign _101_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h1;
  assign _102_ = _103_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:100.6-100.9|ID_stage.v:100.3-211.6" *) 1'hx : _091_;
  assign _104_ = _105_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:100.6-100.9|ID_stage.v:100.3-211.6" *) 1'h0 : _012_;
  assign _106_ = _107_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:100.6-100.9|ID_stage.v:100.3-211.6" *) 3'h0 : _014_;
  assign _108_ = _109_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:100.6-100.9|ID_stage.v:100.3-211.6" *) 1'h0 : _016_;
  assign _110_ = _111_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:100.6-100.9|ID_stage.v:100.3-211.6" *) 1'h0 : _015_;
  function [0:0] _218_;
    input [0:0] a;
    input [12:0] b;
    input [12:0] s;
    (* full_case = 32'd1 *)
    (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *)
    (* parallel_case *)
    casez (s)
      13'b????????????1:
        _218_ = b[0:0];
      13'b???????????1?:
        _218_ = b[1:1];
      13'b??????????1??:
        _218_ = b[2:2];
      13'b?????????1???:
        _218_ = b[3:3];
      13'b????????1????:
        _218_ = b[4:4];
      13'b???????1?????:
        _218_ = b[5:5];
      13'b??????1??????:
        _218_ = b[6:6];
      13'b?????1???????:
        _218_ = b[7:7];
      13'b????1????????:
        _218_ = b[8:8];
      13'b???1?????????:
        _218_ = b[9:9];
      13'b??1??????????:
        _218_ = b[10:10];
      13'b?1???????????:
        _218_ = b[11:11];
      13'b1????????????:
        _218_ = b[12:12];
      default:
        _218_ = a;
    endcase
  endfunction
  assign _112_ = _218_(1'h1, 13'h0000, { _125_, _124_, _123_, _122_, _121_, _120_, _119_, _118_, _117_, _116_, _115_, _114_, _113_ });
  assign _113_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'hc;
  assign _114_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'hb;
  assign _115_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'ha;
  assign _116_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h9;
  assign _117_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h8;
  assign _118_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h7;
  assign _119_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h6;
  assign _120_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h5;
  assign _121_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h4;
  assign _122_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h3;
  assign _123_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h2;
  assign _124_ = ir_op_code_with_bubble == (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) 4'h1;
  assign _125_ = ! (* full_case = 32'd1 *) (* src = "ID_stage.v:0.0-0.0|ID_stage.v:107.4-210.11" *) ir_op_code_with_bubble;
  assign _126_ = _127_ ? (* full_case = 32'd1 *) (* src = "ID_stage.v:100.6-100.9|ID_stage.v:100.3-211.6" *) 1'h0 : _112_;
  assign _128_ = _129_ ? (* src = "ID_stage.v:80.7-80.28|ID_stage.v:80.4-82.7" *) instruction : instruction_reg;
  assign _130_ = _022_ ? (* src = "ID_stage.v:214.33-214.65" *) 32'd1 : 32'd0;
  assign _131_ = _023_ ? (* src = "ID_stage.v:215.32-215.64" *) 32'd1 : 32'd0;
  assign _132_ = alu_src2_mux ? (* src = "ID_stage.v:222.23-222.81" *) { ir_imm[5], ir_imm[5], ir_imm[5], ir_imm[5], ir_imm[5], ir_imm[5], ir_imm[5], ir_imm[5], ir_imm[5], ir_imm[5], ir_imm } : reg_read_data_2;
  assign _133_ = _033_ ? (* src = "ID_stage.v:283.28-289.22" *) 3'h0 : ir_src2;
  assign _134_ = decoding_op_is_store ? (* src = "ID_stage.v:88.19-88.90" *) instruction_reg[11:9] : instruction_reg[5:3];
  assign _135_ = instruction_decode_en ? (* src = "ID_stage.v:93.34-93.76" *) _029_ : 32'd0;
  assign _136_ = instruction_decode_en ? (* src = "ID_stage.v:96.31-96.70" *) _030_ : 32'd0;
  assign ir_op_code = instruction_reg[15:12];
  assign ir_dest = instruction_reg[11:9];
  assign ir_src1 = instruction_reg[8:6];
  assign ir_src2 = _134_;
  assign ir_imm = instruction_reg[5:0];
  assign ir_op_code_with_bubble = _135_[3:0];
  assign ir_dest_with_bubble = _136_[2:0];
  assign decoding_op_is_branch = _130_[0];
  assign decoding_op_is_store = _131_[0];
  assign mem_write_data = reg_read_data_2;
  assign mem_write_en = decoding_op_is_store;
  assign write_back_dest = ir_dest_with_bubble;
  assign ex_alu_src1 = reg_read_data_1;
  assign ex_alu_src2 = _132_;
  assign reg_read_addr_1 = ir_src1;
  assign reg_read_addr_2 = ir_src2;
  assign branch_offset_imm = ir_imm;
  assign decoding_op_src1 = ir_src1;
  assign decoding_op_src2 = _133_;
  assign _001_ = _008_;
  assign _000_ = _007_;
  assign _002_ = _009_;
  assign _006_ = _011_;
  assign _005_ = _010_;
  assign _035_ = _024_;
  assign _039_ = decoding_op_is_branch;
  assign _017_ = _038_;
  assign _043_ = decoding_op_is_branch;
  assign _013_ = _042_;
  assign _045_ = decoding_op_is_branch;
  assign _008_ = _044_;
  assign _049_ = decoding_op_is_branch;
  assign _021_ = _048_;
  assign _004_ = { ex_alu_cmd, reg_read_data_1, _132_, _131_[0], reg_read_data_2, write_back_en, _136_[2:0], write_back_result_mux };
  assign _063_ = rst;
  assign _012_ = _062_;
  assign _077_ = rst;
  assign _014_ = _076_;
  assign _090_ = rst;
  assign _016_ = _089_;
  assign _103_ = rst;
  assign _015_ = _102_;
  assign _105_ = rst;
  assign _007_ = _104_;
  assign _107_ = rst;
  assign _009_ = _106_;
  assign _109_ = rst;
  assign _011_ = _108_;
  assign _111_ = rst;
  assign _010_ = _110_;
  assign _127_ = rst;
  assign _020_ = _126_;
  assign _129_ = instruction_decode_en;
  assign _003_ = _128_;
  assign branch_taken = _044_;
  assign write_back_en = _110_;
  assign write_back_result_mux = _108_;
  assign ex_alu_cmd = _106_;
  assign alu_src2_mux = _104_;
  assign _018_ = rst;
  assign _019_ = rst;
endmodule

(* src = "IF_stage.v:15.1-53.10" *)
module IF_stage(clk, rst, instruction_fetch_en, branch_offset_imm, branch_taken, pc, instruction);
  (* src = "IF_stage.v:29.2-42.5" *)
  wire [7:0] _00_;
  (* src = "IF_stage.v:37.12-37.72" *)
  wire [7:0] _01_;
  (* src = "IF_stage.v:39.12-39.21" *)
  wire [7:0] _02_;
  wire _03_;
  wire [7:0] _04_;
  wire _05_;
  wire [7:0] _06_;
  wire _07_;
  (* src = "IF_stage.v:21.18-21.35" *)
  input [5:0] branch_offset_imm;
  wire [5:0] branch_offset_imm;
  (* src = "IF_stage.v:22.14-22.26" *)
  input branch_taken;
  wire branch_taken;
  (* src = "IF_stage.v:17.14-17.17" *)
  input clk;
  wire clk;
  (* src = "IF_stage.v:25.20-25.31" *)
  output [15:0] instruction;
  wire [15:0] instruction;
  (* src = "IF_stage.v:19.14-19.34" *)
  input instruction_fetch_en;
  wire instruction_fetch_en;
  (* src = "IF_stage.v:24.22-24.24" *)
  output [7:0] pc;
  reg [7:0] pc;
  (* src = "IF_stage.v:18.14-18.17" *)
  input rst;
  wire rst;
  assign _01_ = pc + (* src = "IF_stage.v:37.12-37.72" *) { branch_offset_imm[5], branch_offset_imm[5], branch_offset_imm };
  assign _02_ = pc + (* src = "IF_stage.v:39.12-39.21" *) 8'h01;
  (* src = "IF_stage.v:29.2-42.5" *)
  always @(posedge clk, posedge _03_)
    if (_03_) pc <= 8'h00;
    else pc <= _06_;
  assign _04_ = _05_ ? (* full_case = 32'd1 *) (* src = "IF_stage.v:35.8-35.20|IF_stage.v:35.5-39.22" *) _01_ : _02_;
  assign _06_ = _07_ ? (* src = "IF_stage.v:34.7-34.27|IF_stage.v:34.4-40.7" *) _04_ : pc;
  (* module_not_derived = 32'd1 *)
  (* src = "IF_stage.v:45.18-50.3" *)
  instruction_mem imem (
    .clk(clk),
    .instruction(instruction),
    .pc(pc)
  );
  assign _05_ = branch_taken;
  assign _07_ = instruction_fetch_en;
  assign _00_ = _06_;
  assign _03_ = rst;
endmodule

(* src = "MEM_stage.v:14.1-63.10" *)
module MEM_stage(clk, rst, pipeline_reg_in, pipeline_reg_out, mem_op_dest);
  (* src = "MEM_stage.v:48.2-57.5" *)
  wire [36:0] _00_;
  wire [15:0] _01_;
  wire _02_;
  wire [4:0] _03_;
  wire _04_;
  wire [15:0] _05_;
  wire _06_;
  (* src = "MEM_stage.v:16.12-16.15" *)
  input clk;
  wire clk;
  (* src = "MEM_stage.v:31.15-31.28" *)
  wire [15:0] ex_alu_result;
  (* src = "MEM_stage.v:28.17-28.28" *)
  output [2:0] mem_op_dest;
  wire [2:0] mem_op_dest;
  (* src = "MEM_stage.v:35.15-35.28" *)
  wire [15:0] mem_read_data;
  (* src = "MEM_stage.v:33.15-33.29" *)
  wire [15:0] mem_write_data;
  (* src = "MEM_stage.v:32.10-32.22" *)
  wire mem_write_en;
  (* src = "MEM_stage.v:20.17-20.32" *)
  input [37:0] pipeline_reg_in;
  wire [37:0] pipeline_reg_in;
  (* src = "MEM_stage.v:25.21-25.37" *)
  output [36:0] pipeline_reg_out;
  reg [36:0] pipeline_reg_out;
  (* src = "MEM_stage.v:17.12-17.15" *)
  input rst;
  wire rst;
  (* src = "MEM_stage.v:48.2-57.5" *)
  always @(posedge clk)
    pipeline_reg_out <= { _05_, _01_, _03_ };
  assign _01_ = _02_ ? (* full_case = 32'd1 *) (* src = "MEM_stage.v:49.6-49.9|MEM_stage.v:49.3-56.6" *) 16'h0000 : mem_read_data;
  assign _03_ = _04_ ? (* full_case = 32'd1 *) (* src = "MEM_stage.v:49.6-49.9|MEM_stage.v:49.3-56.6" *) 5'h00 : pipeline_reg_in[4:0];
  assign _05_ = _06_ ? (* full_case = 32'd1 *) (* src = "MEM_stage.v:49.6-49.9|MEM_stage.v:49.3-56.6" *) 16'h0000 : pipeline_reg_in[37:22];
  (* module_not_derived = 32'd1 *)
  (* src = "MEM_stage.v:39.11-45.3" *)
  data_mem dmem (
    .clk(clk),
    .mem_access_addr(ex_alu_result),
    .mem_read_data(mem_read_data),
    .mem_write_data(mem_write_data),
    .mem_write_en(mem_write_en)
  );
  assign ex_alu_result = pipeline_reg_in[37:22];
  assign mem_write_en = pipeline_reg_in[21];
  assign mem_write_data = pipeline_reg_in[20:5];
  assign mem_op_dest = pipeline_reg_in[3:1];
  assign _02_ = rst;
  assign _00_[20:5] = _01_;
  assign _04_ = rst;
  assign _00_[4:0] = _03_;
  assign _06_ = rst;
  assign _00_[36:21] = _05_;
endmodule

(* src = "WB_stage.v:13.1-45.10" *)
module WB_stage(pipeline_reg_in, reg_write_en, reg_write_dest, reg_write_data, wb_op_dest);
  (* src = "WB_stage.v:39.26-39.80" *)
  wire [15:0] _0_;
  (* src = "WB_stage.v:30.14-30.27" *)
  wire [15:0] ex_alu_result;
  (* src = "WB_stage.v:31.14-31.27" *)
  wire [15:0] mem_read_data;
  (* src = "WB_stage.v:18.17-18.32" *)
  input [36:0] pipeline_reg_in;
  wire [36:0] pipeline_reg_in;
  (* src = "WB_stage.v:25.18-25.32" *)
  output [15:0] reg_write_data;
  wire [15:0] reg_write_data;
  (* src = "WB_stage.v:24.17-24.31" *)
  output [2:0] reg_write_dest;
  wire [2:0] reg_write_dest;
  (* src = "WB_stage.v:23.13-23.25" *)
  output reg_write_en;
  wire reg_write_en;
  (* src = "WB_stage.v:27.17-27.27" *)
  output [2:0] wb_op_dest;
  wire [2:0] wb_op_dest;
  (* src = "WB_stage.v:33.13-33.28" *)
  wire [2:0] write_back_dest;
  (* src = "WB_stage.v:32.8-32.21" *)
  wire write_back_en;
  (* src = "WB_stage.v:34.8-34.29" *)
  wire write_back_result_mux;
  assign _0_ = write_back_result_mux ? (* src = "WB_stage.v:39.26-39.80" *) mem_read_data : ex_alu_result;
  assign ex_alu_result = pipeline_reg_in[36:21];
  assign mem_read_data = pipeline_reg_in[20:5];
  assign write_back_en = pipeline_reg_in[4];
  assign write_back_dest = pipeline_reg_in[3:1];
  assign write_back_result_mux = pipeline_reg_in[0];
  assign reg_write_en = write_back_en;
  assign reg_write_dest = write_back_dest;
  assign reg_write_data = _0_;
  assign wb_op_dest = pipeline_reg_in[3:1];
endmodule

(* keep =  1  *)
(* src = "alu.v:13.1-52.10" *)
module alu(a, b, cmd, r);
  (* src = "alu.v:21.2-50.5" *)
  wire [15:0] _00_;
  (* src = "alu.v:21.2-50.5" *)
  wire [15:0] _01_;
  (* src = "alu.v:26.9-26.14" *)
  wire [15:0] _02_;
  (* src = "alu.v:30.9-30.14" *)
  wire [15:0] _03_;
  (* src = "alu.v:45.6-45.53" *)
  wire _04_;
  (* src = "alu.v:32.9-32.14" *)
  wire [15:0] _05_;
  (* src = "alu.v:36.9-36.15" *)
  wire [15:0] _06_;
  (* src = "alu.v:38.9-38.29" *)
  wire [31:0] _07_;
  (* src = "alu.v:40.9-40.23" *)
  wire [31:0] _08_;
  (* src = "alu.v:28.9-28.14" *)
  wire [15:0] _09_;
  (* src = "alu.v:34.9-34.14" *)
  wire [15:0] _10_;
  (* src = "alu.v:15.16-15.17" *)
  input [15:0] a;
  wire [15:0] a;
  (* src = "alu.v:16.16-16.17" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "alu.v:17.15-17.18" *)
  input [2:0] cmd;
  wire [2:0] cmd;
  (* src = "alu.v:19.20-19.21" *)
  output [15:0] r;
  wire [15:0] r;
  assign _02_ = a + (* src = "alu.v:26.9-26.14" *) b;
  assign _03_ = a & (* src = "alu.v:30.9-30.14" *) b;
  always @*
    if (1'h0)
      $write("ERROR: Unknown alu cmd: %03b \n\n", $unsigned(cmd));
  assign _05_ = a | (* src = "alu.v:32.9-32.14" *) b;
  assign _06_ = a << (* src = "alu.v:36.9-36.15" *) b;
  assign _07_ = { a[15], a[15], a[15], a[15], a[15], a[15], a[15], a[15], a[15], a[15], a[15], a[15], a[15], a[15], a[15], a[15], a } >> (* src = "alu.v:38.9-38.29" *) b;
  assign _08_ = { 16'h0000, a } >> (* src = "alu.v:40.9-40.23" *) b;
  assign _09_ = a - (* src = "alu.v:28.9-28.14" *) b;
  assign _10_ = a ^ (* src = "alu.v:34.9-34.14" *) b;
  assign _00_ = _01_;
  assign _04_ = 1'h0;
  assign _01_ = 16'hxxxx;
  assign r = 16'hxxxx;
endmodule

(* src = "data_mem.v:14.1-40.10" *)
module data_mem(clk, mem_access_addr, mem_write_data, mem_write_en, mem_read_data);
  (* src = "data_mem.v:34.2-36.36" *)
  wire [7:0] _00_;
  (* src = "data_mem.v:34.2-36.36" *)
  wire [15:0] _01_;
  (* src = "data_mem.v:34.2-36.36" *)
  wire [15:0] _02_;
  (* src = "data_mem.v:34.2-36.36" *)
  wire [7:0] _03_;
  (* src = "data_mem.v:34.2-36.36" *)
  wire [15:0] _04_;
  (* src = "data_mem.v:34.2-36.36" *)
  wire [15:0] _05_;
  (* src = "data_mem.v:38.25-38.28" *)
  wire [15:0] _06_;
  (* src = "data_mem.v:0.0-0.0" *)
  reg [7:0] _07_;
  (* src = "data_mem.v:0.0-0.0" *)
  reg [15:0] _08_;
  (* src = "data_mem.v:0.0-0.0" *)
  reg [15:0] _09_;
  wire [15:0] _10_;
  wire _11_;
  wire [15:0] _12_;
  wire _13_;
  wire [7:0] _14_;
  wire _15_;
  (* src = "data_mem.v:16.12-16.15" *)
  input clk;
  wire clk;
  (* src = "data_mem.v:19.17-19.32" *)
  input [15:0] mem_access_addr;
  wire [15:0] mem_access_addr;
  (* src = "data_mem.v:25.18-25.31" *)
  output [15:0] mem_read_data;
  wire [15:0] mem_read_data;
  (* src = "data_mem.v:22.17-22.31" *)
  input [15:0] mem_write_data;
  wire [15:0] mem_write_data;
  (* src = "data_mem.v:23.12-23.24" *)
  input mem_write_en;
  wire mem_write_en;
  (* src = "data_mem.v:32.17-32.25" *)
  wire [7:0] ram_addr;
  (* src = "data_mem.v:30.13-30.16" *)
  reg [15:0] ram [255:0];
  always @(posedge clk) begin
    if (_05_[0])
      ram[_03_][0:0] <= _04_[0];
    if (_05_[1])
      ram[_03_][1:1] <= _04_[1];
    if (_05_[2])
      ram[_03_][2:2] <= _04_[2];
    if (_05_[3])
      ram[_03_][3:3] <= _04_[3];
    if (_05_[4])
      ram[_03_][4:4] <= _04_[4];
    if (_05_[5])
      ram[_03_][5:5] <= _04_[5];
    if (_05_[6])
      ram[_03_][6:6] <= _04_[6];
    if (_05_[7])
      ram[_03_][7:7] <= _04_[7];
    if (_05_[8])
      ram[_03_][8:8] <= _04_[8];
    if (_05_[9])
      ram[_03_][9:9] <= _04_[9];
    if (_05_[10])
      ram[_03_][10:10] <= _04_[10];
    if (_05_[11])
      ram[_03_][11:11] <= _04_[11];
    if (_05_[12])
      ram[_03_][12:12] <= _04_[12];
    if (_05_[13])
      ram[_03_][13:13] <= _04_[13];
    if (_05_[14])
      ram[_03_][14:14] <= _04_[14];
    if (_05_[15])
      ram[_03_][15:15] <= _04_[15];
  end
  assign _06_ = ram[ram_addr];
  (* src = "data_mem.v:34.2-36.36" *)
  always @(posedge clk)
    _07_ <= _14_;
  (* src = "data_mem.v:34.2-36.36" *)
  always @(posedge clk)
    _08_ <= _12_;
  (* src = "data_mem.v:34.2-36.36" *)
  always @(posedge clk)
    _09_ <= _10_;
  assign _10_ = _11_ ? (* full_case = 32'd1 *) (* src = "data_mem.v:35.7-35.19|data_mem.v:35.3-36.36" *) 16'hffff : 16'h0000;
  assign _12_ = _13_ ? (* full_case = 32'd1 *) (* src = "data_mem.v:35.7-35.19|data_mem.v:35.3-36.36" *) mem_write_data : 16'hxxxx;
  assign _14_ = _15_ ? (* full_case = 32'd1 *) (* src = "data_mem.v:35.7-35.19|data_mem.v:35.3-36.36" *) mem_access_addr[7:0] : 8'hxx;
  assign ram_addr = mem_access_addr[7:0];
  assign mem_read_data = _06_;
  assign _02_ = _05_;
  assign _01_ = _04_;
  assign _00_ = _03_;
  assign _11_ = mem_write_en;
  assign _05_ = _10_;
  assign _13_ = mem_write_en;
  assign _04_ = _12_;
  assign _15_ = mem_write_en;
  assign _03_ = _14_;
endmodule

(* src = "hazard_detection_unit.v:20.1-58.10" *)
module hazard_detection_unit(decoding_op_src1, decoding_op_src2, ex_op_dest, mem_op_dest, wb_op_dest, pipeline_stall_n);
  (* src = "hazard_detection_unit.v:32.2-54.5" *)
  wire _00_;
  (* src = "hazard_detection_unit.v:32.2-54.5" *)
  wire _01_;
  (* src = "hazard_detection_unit.v:32.2-54.5" *)
  wire _02_;
  (* src = "hazard_detection_unit.v:37.5-37.35" *)
  wire _03_;
  (* src = "hazard_detection_unit.v:38.5-38.36" *)
  wire _04_;
  (* src = "hazard_detection_unit.v:39.5-39.35" *)
  wire _05_;
  (* src = "hazard_detection_unit.v:46.5-46.35" *)
  wire _06_;
  (* src = "hazard_detection_unit.v:47.5-47.36" *)
  wire _07_;
  (* src = "hazard_detection_unit.v:48.5-48.35" *)
  wire _08_;
  (* src = "hazard_detection_unit.v:35.7-40.5" *)
  wire _09_;
  (* src = "hazard_detection_unit.v:44.7-49.5" *)
  wire _10_;
  (* src = "hazard_detection_unit.v:37.5-38.36" *)
  wire _11_;
  (* src = "hazard_detection_unit.v:37.5-39.35" *)
  wire _12_;
  (* src = "hazard_detection_unit.v:46.5-47.36" *)
  wire _13_;
  (* src = "hazard_detection_unit.v:46.5-48.35" *)
  wire _14_;
  (* src = "hazard_detection_unit.v:35.7-35.28" *)
  wire _15_;
  (* src = "hazard_detection_unit.v:44.7-44.28" *)
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  (* src = "hazard_detection_unit.v:22.16-22.32" *)
  input [2:0] decoding_op_src1;
  wire [2:0] decoding_op_src1;
  (* src = "hazard_detection_unit.v:23.16-23.32" *)
  input [2:0] decoding_op_src2;
  wire [2:0] decoding_op_src2;
  (* src = "hazard_detection_unit.v:25.16-25.26" *)
  input [2:0] ex_op_dest;
  wire [2:0] ex_op_dest;
  (* src = "hazard_detection_unit.v:26.16-26.27" *)
  input [2:0] mem_op_dest;
  wire [2:0] mem_op_dest;
  (* src = "hazard_detection_unit.v:29.16-29.32" *)
  output pipeline_stall_n;
  wire pipeline_stall_n;
  (* src = "hazard_detection_unit.v:27.16-27.26" *)
  input [2:0] wb_op_dest;
  wire [2:0] wb_op_dest;
  assign _03_ = decoding_op_src1 == (* src = "hazard_detection_unit.v:37.5-37.35" *) ex_op_dest;
  assign _04_ = decoding_op_src1 == (* src = "hazard_detection_unit.v:38.5-38.36" *) mem_op_dest;
  assign _05_ = decoding_op_src1 == (* src = "hazard_detection_unit.v:39.5-39.35" *) wb_op_dest;
  assign _06_ = decoding_op_src2 == (* src = "hazard_detection_unit.v:46.5-46.35" *) ex_op_dest;
  assign _07_ = decoding_op_src2 == (* src = "hazard_detection_unit.v:47.5-47.36" *) mem_op_dest;
  assign _08_ = decoding_op_src2 == (* src = "hazard_detection_unit.v:48.5-48.35" *) wb_op_dest;
  assign _09_ = _15_ && (* src = "hazard_detection_unit.v:35.7-40.5" *) _12_;
  assign _10_ = _16_ && (* src = "hazard_detection_unit.v:44.7-49.5" *) _14_;
  assign _11_ = _03_ || (* src = "hazard_detection_unit.v:37.5-38.36" *) _04_;
  assign _12_ = _11_ || (* src = "hazard_detection_unit.v:37.5-39.35" *) _05_;
  assign _13_ = _06_ || (* src = "hazard_detection_unit.v:46.5-47.36" *) _07_;
  assign _14_ = _13_ || (* src = "hazard_detection_unit.v:46.5-48.35" *) _08_;
  assign _15_ = | (* src = "hazard_detection_unit.v:35.7-35.28" *) decoding_op_src1;
  assign _16_ = | (* src = "hazard_detection_unit.v:44.7-44.28" *) decoding_op_src2;
  assign _17_ = _18_ ? (* full_case = 32'd1 *) (* src = "hazard_detection_unit.v:44.7-49.5|hazard_detection_unit.v:44.3-51.25" *) 1'h0 : _01_;
  assign _19_ = _20_ ? (* full_case = 32'd1 *) (* src = "hazard_detection_unit.v:35.7-40.5|hazard_detection_unit.v:35.3-42.25" *) 1'h0 : 1'h1;
  assign _00_ = _02_;
  assign _18_ = _10_;
  assign _02_ = _17_;
  assign _20_ = _09_;
  assign _01_ = _19_;
  assign pipeline_stall_n = _17_;
endmodule

(* src = "instruction_mem.v:15.1-35.10" *)
module instruction_mem(clk, pc, instruction);
  (* src = "instruction_mem.v:32.23-32.26" *)
  wire [15:0] _0_;
  (* src = "instruction_mem.v:17.12-17.15" *)
  input clk;
  wire clk;
  (* src = "instruction_mem.v:20.18-20.29" *)
  output [15:0] instruction;
  wire [15:0] instruction;
  (* src = "instruction_mem.v:18.16-18.18" *)
  input [7:0] pc;
  wire [7:0] pc;
  (* src = "instruction_mem.v:25.17-25.25" *)
  wire [7:0] rom_addr;
  (* src = "instruction_mem.v:23.13-23.16" *)
  reg [15:0] rom [255:0];
  assign _0_ = rom[rom_addr];
  assign rom_addr = pc;
  assign instruction = _0_;
endmodule

(* keep =  1  *)
(* top =  1  *)
(* src = "mips_16_core_top.v:18.1-117.10" *)
module mips_16_core_top(clk, rst, pc);
  (* src = "mips_16_core_top.v:30.17-30.36" *)
  wire [37:0] EX_pipeline_reg_out;
  (* src = "mips_16_core_top.v:29.17-29.36" *)
  wire [56:0] ID_pipeline_reg_out;
  (* src = "mips_16_core_top.v:31.17-31.37" *)
  wire [36:0] MEM_pipeline_reg_out;
  (* src = "mips_16_core_top.v:26.16-26.33" *)
  wire [5:0] branch_offset_imm;
  (* src = "mips_16_core_top.v:27.12-27.24" *)
  wire branch_taken;
  (* src = "mips_16_core_top.v:20.13-20.16" *)
  input clk;
  wire clk;
  (* src = "mips_16_core_top.v:37.16-37.32" *)
  wire [2:0] decoding_op_src1;
  (* src = "mips_16_core_top.v:38.16-38.32" *)
  wire [2:0] decoding_op_src2;
  (* src = "mips_16_core_top.v:39.16-39.26" *)
  wire [2:0] ex_op_dest;
  (* src = "mips_16_core_top.v:28.17-28.28" *)
  wire [15:0] instruction;
  (* src = "mips_16_core_top.v:40.16-40.27" *)
  wire [2:0] mem_op_dest;
  (* src = "mips_16_core_top.v:23.18-23.20" *)
  output [7:0] pc;
  wire [7:0] pc;
  (* src = "mips_16_core_top.v:25.13-25.29" *)
  wire pipeline_stall_n;
  (* src = "mips_16_core_top.v:33.16-33.31" *)
  wire [2:0] reg_read_addr_1;
  (* src = "mips_16_core_top.v:34.16-34.31" *)
  wire [2:0] reg_read_addr_2;
  (* src = "mips_16_core_top.v:35.17-35.32" *)
  wire [15:0] reg_read_data_1;
  (* src = "mips_16_core_top.v:36.17-36.32" *)
  wire [15:0] reg_read_data_2;
  (* src = "mips_16_core_top.v:44.17-44.31" *)
  wire [15:0] reg_write_data;
  (* src = "mips_16_core_top.v:43.16-43.30" *)
  wire [2:0] reg_write_dest;
  (* src = "mips_16_core_top.v:42.12-42.24" *)
  wire reg_write_en;
  (* src = "mips_16_core_top.v:21.13-21.16" *)
  input rst;
  wire rst;
  (* src = "mips_16_core_top.v:41.16-41.26" *)
  wire [2:0] wb_op_dest;
  (* module_not_derived = 32'd1 *)
  (* src = "mips_16_core_top.v:72.11-78.3" *)
  EX_stage EX_stage_inst (
    .clk(clk),
    .ex_op_dest(ex_op_dest),
    .pipeline_reg_in(ID_pipeline_reg_out),
    .pipeline_reg_out(EX_pipeline_reg_out),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mips_16_core_top.v:56.11-70.3" *)
  ID_stage ID_stage_inst (
    .branch_offset_imm(branch_offset_imm),
    .branch_taken(branch_taken),
    .clk(clk),
    .decoding_op_src1(decoding_op_src1),
    .decoding_op_src2(decoding_op_src2),
    .instruction(instruction),
    .instruction_decode_en(pipeline_stall_n),
    .pipeline_reg_out(ID_pipeline_reg_out),
    .reg_read_addr_1(reg_read_addr_1),
    .reg_read_addr_2(reg_read_addr_2),
    .reg_read_data_1(reg_read_data_1),
    .reg_read_data_2(reg_read_data_2),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mips_16_core_top.v:46.11-54.3" *)
  IF_stage IF_stage_inst (
    .branch_offset_imm(branch_offset_imm),
    .branch_taken(branch_taken),
    .clk(clk),
    .instruction(instruction),
    .instruction_fetch_en(pipeline_stall_n),
    .pc(pc),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mips_16_core_top.v:80.12-86.3" *)
  MEM_stage MEM_stage_inst (
    .clk(clk),
    .mem_op_dest(mem_op_dest),
    .pipeline_reg_in(EX_pipeline_reg_out),
    .pipeline_reg_out(MEM_pipeline_reg_out),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mips_16_core_top.v:88.11-94.3" *)
  WB_stage WB_stage_inst (
    .pipeline_reg_in(MEM_pipeline_reg_out),
    .reg_write_data(reg_write_data),
    .reg_write_dest(reg_write_dest),
    .reg_write_en(reg_write_en),
    .wb_op_dest(wb_op_dest)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mips_16_core_top.v:108.24-115.3" *)
  hazard_detection_unit hazard_detection_unit_inst (
    .decoding_op_src1(decoding_op_src1),
    .decoding_op_src2(decoding_op_src2),
    .ex_op_dest(ex_op_dest),
    .mem_op_dest(mem_op_dest),
    .pipeline_stall_n(pipeline_stall_n),
    .wb_op_dest(wb_op_dest)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mips_16_core_top.v:96.16-106.3" *)
  register_file register_file_inst (
    .clk(clk),
    .reg_read_addr_1(reg_read_addr_1),
    .reg_read_addr_2(reg_read_addr_2),
    .reg_read_data_1(reg_read_data_1),
    .reg_read_data_2(reg_read_data_2),
    .reg_write_data(reg_write_data),
    .reg_write_dest(reg_write_dest),
    .reg_write_en(reg_write_en),
    .rst(rst)
  );
endmodule

(* src = "register_file.v:18.1-82.10" *)
module register_file(clk, rst, reg_write_en, reg_write_dest, reg_write_data, reg_read_addr_1, reg_read_data_1, reg_read_addr_2, reg_read_data_2);
  (* src = "register_file.v:0.0-0.0" *)
  wire [15:0] _000_;
  (* src = "register_file.v:0.0-0.0" *)
  wire [15:0] _001_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [2:0] _002_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [15:0] _003_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [15:0] _004_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [15:0] _005_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [15:0] _006_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [15:0] _007_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [15:0] _008_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [15:0] _009_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [15:0] _010_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [15:0] _011_;
  (* src = "register_file.v:0.0-0.0" *)
  wire [15:0] _012_;
  (* src = "register_file.v:0.0-0.0" *)
  wire [15:0] _013_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [2:0] _014_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [15:0] _015_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [2:0] _016_;
  (* src = "register_file.v:39.2-58.5" *)
  wire [15:0] _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  (* src = "register_file.v:69.29-69.49" *)
  wire _028_;
  (* src = "register_file.v:80.29-80.49" *)
  wire _029_;
  (* src = "register_file.v:69.27-69.86" *)
  wire [15:0] _030_;
  (* src = "register_file.v:80.27-80.86" *)
  wire [15:0] _031_;
  (* src = "register_file.v:0.0-0.0" *)
  wire [2:0] _032_;
  (* src = "register_file.v:0.0-0.0" *)
  wire [15:0] _033_;
  (* src = "register_file.v:0.0-0.0" *)
  wire [2:0] _034_;
  (* src = "register_file.v:0.0-0.0" *)
  wire [15:0] _035_;
  (* nosync = 32'd1 *)
  (* src = "register_file.v:0.0-0.0" *)
  reg [2:0] _036_;
  (* nosync = 32'd1 *)
  (* src = "register_file.v:0.0-0.0" *)
  reg [15:0] _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire [2:0] _045_;
  wire _046_;
  wire [15:0] _047_;
  wire _048_;
  wire [15:0] _049_;
  wire _050_;
  wire [15:0] _051_;
  wire _052_;
  wire [15:0] _053_;
  wire _054_;
  wire [15:0] _055_;
  wire _056_;
  wire [15:0] _057_;
  wire _058_;
  wire [15:0] _059_;
  wire _060_;
  wire [15:0] _061_;
  wire _062_;
  wire [15:0] _063_;
  wire _064_;
  wire [15:0] _065_;
  wire _066_;
  wire [15:0] _067_;
  wire _068_;
  wire [15:0] _069_;
  wire _070_;
  wire [15:0] _071_;
  wire _072_;
  wire [15:0] _073_;
  wire _074_;
  wire [15:0] _075_;
  wire _076_;
  wire [15:0] _077_;
  wire _078_;
  wire [15:0] _079_;
  wire _080_;
  wire [15:0] _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire [15:0] _090_;
  wire _091_;
  (* src = "register_file.v:69.27-69.86" *)
  wire [15:0] _092_;
  (* src = "register_file.v:80.27-80.86" *)
  wire [15:0] _093_;
  (* src = "register_file.v:20.11-20.14" *)
  input clk;
  wire clk;
  (* src = "register_file.v:35.13-35.22" *)
  reg [15:0] \reg_array[0] ;
  (* src = "register_file.v:35.13-35.22" *)
  reg [15:0] \reg_array[1] ;
  (* src = "register_file.v:35.13-35.22" *)
  reg [15:0] \reg_array[2] ;
  (* src = "register_file.v:35.13-35.22" *)
  reg [15:0] \reg_array[3] ;
  (* src = "register_file.v:35.13-35.22" *)
  reg [15:0] \reg_array[4] ;
  (* src = "register_file.v:35.13-35.22" *)
  reg [15:0] \reg_array[5] ;
  (* src = "register_file.v:35.13-35.22" *)
  reg [15:0] \reg_array[6] ;
  (* src = "register_file.v:35.13-35.22" *)
  reg [15:0] \reg_array[7] ;
  (* src = "register_file.v:29.15-29.30" *)
  input [2:0] reg_read_addr_1;
  wire [2:0] reg_read_addr_1;
  (* src = "register_file.v:32.15-32.30" *)
  input [2:0] reg_read_addr_2;
  wire [2:0] reg_read_addr_2;
  (* src = "register_file.v:30.17-30.32" *)
  output [15:0] reg_read_data_1;
  wire [15:0] reg_read_data_1;
  (* src = "register_file.v:33.17-33.32" *)
  output [15:0] reg_read_data_2;
  wire [15:0] reg_read_data_2;
  (* src = "register_file.v:26.16-26.30" *)
  input [15:0] reg_write_data;
  wire [15:0] reg_write_data;
  (* src = "register_file.v:25.15-25.29" *)
  input [2:0] reg_write_dest;
  wire [2:0] reg_write_dest;
  (* src = "register_file.v:24.11-24.23" *)
  input reg_write_en;
  wire reg_write_en;
  (* src = "register_file.v:21.11-21.14" *)
  input rst;
  wire rst;
  assign _028_ = ! (* src = "register_file.v:69.29-69.49" *) reg_read_addr_1;
  assign _029_ = ! (* src = "register_file.v:80.29-80.49" *) reg_read_addr_2;
  (* src = "register_file.v:39.2-58.5" *)
  always @(posedge clk, posedge _018_)
    if (_018_) \reg_array[0]  <= 16'h0000;
    else \reg_array[0]  <= _079_;
  (* src = "register_file.v:39.2-58.5" *)
  always @(posedge clk, posedge _019_)
    if (_019_) \reg_array[1]  <= 16'h0000;
    else \reg_array[1]  <= _075_;
  (* src = "register_file.v:39.2-58.5" *)
  always @(posedge clk, posedge _020_)
    if (_020_) \reg_array[2]  <= 16'h0000;
    else \reg_array[2]  <= _071_;
  (* src = "register_file.v:39.2-58.5" *)
  always @(posedge clk, posedge _021_)
    if (_021_) \reg_array[3]  <= 16'h0000;
    else \reg_array[3]  <= _067_;
  (* src = "register_file.v:39.2-58.5" *)
  always @(posedge clk, posedge _022_)
    if (_022_) \reg_array[4]  <= 16'h0000;
    else \reg_array[4]  <= _063_;
  (* src = "register_file.v:39.2-58.5" *)
  always @(posedge clk, posedge _023_)
    if (_023_) \reg_array[5]  <= 16'h0000;
    else \reg_array[5]  <= _059_;
  (* src = "register_file.v:39.2-58.5" *)
  always @(posedge clk, posedge _024_)
    if (_024_) \reg_array[6]  <= 16'h0000;
    else \reg_array[6]  <= _055_;
  (* src = "register_file.v:39.2-58.5" *)
  always @(posedge clk, posedge _025_)
    if (_025_) \reg_array[7]  <= 16'h0000;
    else \reg_array[7]  <= _051_;
  (* src = "register_file.v:39.2-58.5" *)
  always @(posedge clk, posedge _026_)
    if (_026_) _036_ <= 3'hx;
    else _036_ <= 3'hx;
  (* src = "register_file.v:39.2-58.5" *)
  always @(posedge clk, posedge _027_)
    if (_027_) _037_ <= 16'hxxxx;
    else _037_ <= 16'hxxxx;
  assign _038_ = _032_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h6;
  assign _039_ = _032_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h5;
  assign _040_ = _032_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h4;
  assign _041_ = _032_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h3;
  assign _042_ = _032_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h2;
  assign _043_ = _032_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h1;
  assign _044_ = ! (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) _032_;
  assign _045_ = _046_ ? (* full_case = 32'd1 *) (* src = "register_file.v:53.7-53.19|register_file.v:53.4-55.7" *) reg_write_dest : _036_;
  assign _047_ = _048_ ? (* full_case = 32'd1 *) (* src = "register_file.v:53.7-53.19|register_file.v:53.4-55.7" *) reg_write_data : _037_;
  assign _049_ = _050_ ? (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) reg_write_data : \reg_array[7] ;
  assign _050_ = reg_write_dest == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h7;
  assign _051_ = _052_ ? (* full_case = 32'd1 *) (* src = "register_file.v:53.7-53.19|register_file.v:53.4-55.7" *) _049_ : \reg_array[7] ;
  assign _053_ = _054_ ? (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) reg_write_data : \reg_array[6] ;
  assign _054_ = reg_write_dest == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h6;
  assign _055_ = _056_ ? (* full_case = 32'd1 *) (* src = "register_file.v:53.7-53.19|register_file.v:53.4-55.7" *) _053_ : \reg_array[6] ;
  assign _057_ = _058_ ? (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) reg_write_data : \reg_array[5] ;
  assign _058_ = reg_write_dest == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h5;
  assign _059_ = _060_ ? (* full_case = 32'd1 *) (* src = "register_file.v:53.7-53.19|register_file.v:53.4-55.7" *) _057_ : \reg_array[5] ;
  assign _061_ = _062_ ? (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) reg_write_data : \reg_array[4] ;
  assign _062_ = reg_write_dest == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h4;
  assign _063_ = _064_ ? (* full_case = 32'd1 *) (* src = "register_file.v:53.7-53.19|register_file.v:53.4-55.7" *) _061_ : \reg_array[4] ;
  assign _065_ = _066_ ? (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) reg_write_data : \reg_array[3] ;
  assign _066_ = reg_write_dest == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h3;
  assign _067_ = _068_ ? (* full_case = 32'd1 *) (* src = "register_file.v:53.7-53.19|register_file.v:53.4-55.7" *) _065_ : \reg_array[3] ;
  assign _069_ = _070_ ? (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) reg_write_data : \reg_array[2] ;
  assign _070_ = reg_write_dest == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h2;
  assign _071_ = _072_ ? (* full_case = 32'd1 *) (* src = "register_file.v:53.7-53.19|register_file.v:53.4-55.7" *) _069_ : \reg_array[2] ;
  assign _073_ = _074_ ? (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) reg_write_data : \reg_array[1] ;
  assign _074_ = reg_write_dest == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h1;
  assign _075_ = _076_ ? (* full_case = 32'd1 *) (* src = "register_file.v:53.7-53.19|register_file.v:53.4-55.7" *) _073_ : \reg_array[1] ;
  assign _077_ = _078_ ? (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) reg_write_data : \reg_array[0] ;
  assign _078_ = ! (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) reg_write_dest;
  assign _079_ = _080_ ? (* full_case = 32'd1 *) (* src = "register_file.v:53.7-53.19|register_file.v:53.4-55.7" *) _077_ : \reg_array[0] ;
  function [15:0] _139_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    (* full_case = 32'd1 *)
    (* src = "register_file.v:0.0-0.0" *)
    (* parallel_case *)
    casez (s)
      8'b???????1:
        _139_ = b[15:0];
      8'b??????1?:
        _139_ = b[31:16];
      8'b?????1??:
        _139_ = b[47:32];
      8'b????1???:
        _139_ = b[63:48];
      8'b???1????:
        _139_ = b[79:64];
      8'b??1?????:
        _139_ = b[95:80];
      8'b?1??????:
        _139_ = b[111:96];
      8'b1???????:
        _139_ = b[127:112];
      default:
        _139_ = a;
    endcase
  endfunction
  assign _081_ = _139_(16'hxxxx, { \reg_array[0] , \reg_array[1] , \reg_array[2] , \reg_array[3] , \reg_array[4] , \reg_array[5] , \reg_array[6] , \reg_array[7]  }, { _089_, _088_, _087_, _086_, _085_, _084_, _083_, _082_ });
  assign _082_ = _034_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h7;
  assign _083_ = _034_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h6;
  assign _084_ = _034_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h5;
  assign _085_ = _034_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h4;
  assign _086_ = _034_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h3;
  assign _087_ = _034_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h2;
  assign _088_ = _034_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h1;
  assign _089_ = ! (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) _034_;
  function [15:0] _148_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    (* full_case = 32'd1 *)
    (* src = "register_file.v:0.0-0.0" *)
    (* parallel_case *)
    casez (s)
      8'b???????1:
        _148_ = b[15:0];
      8'b??????1?:
        _148_ = b[31:16];
      8'b?????1??:
        _148_ = b[47:32];
      8'b????1???:
        _148_ = b[63:48];
      8'b???1????:
        _148_ = b[79:64];
      8'b??1?????:
        _148_ = b[95:80];
      8'b?1??????:
        _148_ = b[111:96];
      8'b1???????:
        _148_ = b[127:112];
      default:
        _148_ = a;
    endcase
  endfunction
  assign _090_ = _148_(16'hxxxx, { \reg_array[0] , \reg_array[1] , \reg_array[2] , \reg_array[3] , \reg_array[4] , \reg_array[5] , \reg_array[6] , \reg_array[7]  }, { _044_, _043_, _042_, _041_, _040_, _039_, _038_, _091_ });
  assign _091_ = _032_ == (* full_case = 32'd1 *) (* src = "register_file.v:0.0-0.0" *) 3'h7;
  assign _092_ = _028_ ? (* src = "register_file.v:69.27-69.86" *) 16'h0000 : _033_;
  assign _093_ = _029_ ? (* src = "register_file.v:80.27-80.86" *) 16'h0000 : _035_;
  assign reg_read_data_1 = _092_;
  assign reg_read_data_2 = _093_;
  assign _032_ = reg_read_addr_1;
  assign _034_ = reg_read_addr_2;
  assign _001_ = _013_;
  assign _000_ = _012_;
  assign _003_ = _015_;
  assign _002_ = _014_;
  assign _013_ = _081_;
  assign _012_ = _090_;
  assign _046_ = reg_write_en;
  assign _016_ = _045_;
  assign _048_ = reg_write_en;
  assign _017_ = _047_;
  assign _015_ = _017_;
  assign _014_ = _016_;
  assign _052_ = reg_write_en;
  assign _011_ = _051_;
  assign _056_ = reg_write_en;
  assign _010_ = _055_;
  assign _060_ = reg_write_en;
  assign _009_ = _059_;
  assign _064_ = reg_write_en;
  assign _008_ = _063_;
  assign _068_ = reg_write_en;
  assign _007_ = _067_;
  assign _072_ = reg_write_en;
  assign _006_ = _071_;
  assign _076_ = reg_write_en;
  assign _005_ = _075_;
  assign _080_ = reg_write_en;
  assign _004_ = _079_;
  assign _035_ = _081_;
  assign _033_ = _090_;
  assign _030_ = 16'h0000;
  assign _031_ = 16'h0000;
  assign _018_ = rst;
  assign _019_ = rst;
  assign _020_ = rst;
  assign _021_ = rst;
  assign _022_ = rst;
  assign _023_ = rst;
  assign _024_ = rst;
  assign _025_ = rst;
  assign _026_ = rst;
  assign _027_ = rst;
endmodule
